// src/catalog/classification.ts — GENERATED by scripts/refresh-classification.mjs. Do not edit.
//
// Per-model reasoning capability, derived any-true-wins across the
// models.md efforts entries, the `reasoning` flag on the Command Code
// docs' RSC slug records (plans/goat + plans/pro, slug-id aliasing
// applied, keyed by snapshot id), and the models page Caps Reasoning
// bit (issue #132). The map is sparse: only models with evidence get an
// entry (true = any channel fires; false = checked evidence is
// all-negative). Models with NO evidence anywhere ship in
// MODEL_REASONING_PENDING — they behave as non-reasoning at runtime and
// flip with zero code when evidence arrives. Classification is
// upstream-managed and derived, never hand-maintained; the only human
// seam is CLASSIFICATION_OVERRIDES, whose entries each carry a written
// justification naming the upstream disagreement (see ADR-0006).
// Regenerate with `npm run refresh` (offline:
// `npm run refresh:classification -- --fixtures`).

export const CLASSIFICATION_SOURCE_URLS: ReadonlyArray<string> = [
  "https://commandcode.ai/docs/plans/goat",
  "https://commandcode.ai/docs/plans/pro",
]

export const CLASSIFICATION_LAST_REFRESHED = "2026-09-10"

// Active capability overrides. Empty = upstream data is truth.
// Every entry requires a written justification naming the upstream
// disagreement; entries are rendered into the refresh PR body.
export const CLASSIFICATION_OVERRIDES: Readonly<Record<string, { capability: boolean; justification: string }>> = {
}

// Snapshot models with no capability evidence anywhere (no RSC record,
// no models.md efforts, no models page Reasoning bit). They behave as
// non-reasoning and land in this bucket until evidence arrives — the
// next refresh moves them into MODEL_REASONING_CAPABILITY with zero code.
export const MODEL_REASONING_PENDING: ReadonlyArray<string> = [
]

export const MODEL_REASONING_CAPABILITY: Readonly<Record<string, boolean>> = {
  "claude-fable-5": true,
  "claude-fable-5-1": true,
  "claude-haiku-4-5-20251001": false,
  "claude-opus-4-7": true,
  "claude-opus-4-8": true,
  "claude-opus-5": true,
  "claude-sonnet-4-6": true,
  "claude-sonnet-5": true,
  "deepseek/deepseek-v4-flash": true,
  "deepseek/deepseek-v4-flash-fast": true,
  "deepseek/deepseek-v4-flash-vision-exp": true,
  "deepseek/deepseek-v4-pro": true,
  "deepseek/deepseek-v4.1-flash": true,
  "google/gemini-3.1-flash-lite": true,
  "google/gemini-3.5-flash": true,
  "google/gemini-3.5-flash-lite": true,
  "google/gemini-3.6-flash": true,
  "google/gemini-3.7-flash": true,
  "google/gemini-3.8-flash": true,
  "gpt-5.3-codex": true,
  "gpt-5.4": true,
  "gpt-5.4-mini": true,
  "gpt-5.5": true,
  "gpt-5.6-luna": true,
  "gpt-5.6-sol": true,
  "gpt-5.6-terra": true,
  "gpt-6-astra": true,
  "inclusionai/ling-3.0-flash-sante:free": true,
  "meituan/LongCat-2.0:free": true,
  "meta/muse-spark-1.1": true,
  "meta/muse-spark-1.2": true,
  "meta/muse-spark-1.2-contributor": true,
  "meta/muse-spark-1.3": true,
  "meta/muse-spark-1.3-contributor": true,
  "MiniMaxAI/MiniMax-M2.5": false,
  "MiniMaxAI/MiniMax-M2.7": false,
  "MiniMaxAI/MiniMax-M3": true,
  "moonshotai/Kimi-K2.5": false,
  "moonshotai/Kimi-K2.6": false,
  "moonshotai/Kimi-K2.7-Code": true,
  "moonshotai/Kimi-K2.7-Code-Highspeed": true,
  "moonshotai/Kimi-K3": true,
  "nvidia/nemotron-3-ultra-550b-a55b": true,
  "poolside/laguna-s-2.1-free": true,
  "Qwen/Qwen3.6-Max-Preview": true,
  "Qwen/Qwen3.6-Plus": true,
  "Qwen/Qwen3.7-Flash": true,
  "Qwen/Qwen3.7-Max": true,
  "Qwen/Qwen3.7-Plus": true,
  "Qwen/Qwen3.8-27B": true,
  "Qwen/Qwen3.8-Flash": true,
  "Qwen/Qwen3.8-Max": true,
  "Qwen/Qwen3.8-Max-0902": true,
  "sakana/fugu-ultra": true,
  "stepfun/Step-3.5-Flash": true,
  "stepfun/Step-3.7-Flash": true,
  "tencent/hy3-paid": true,
  "tencent/hy4-preview": true,
  "thinkingmachines/inkling": true,
  "thinkingmachines/inkling-small": true,
  "xai/grok-4.5": true,
  "xai/grok-4.6": true,
  "xiaomi/mimo-v2.5": false,
  "xiaomi/mimo-v2.5-pro": false,
  "z-ai/glm-5.3-flash": true,
  "zai-org/GLM-5": false,
  "zai-org/GLM-5.1": false,
  "zai-org/GLM-5.2": true,
  "zai-org/GLM-5.2-Fast": false,
  "zai-org/GLM-5.3": true,
}
