// src/catalog/deals.ts — GENERATED by scripts/refresh-deals.mjs. Do not edit.
//
// Deal/allowance/benchmark intelligence parsed from the Command Code docs
// site (pricing-limits, plans/goat, plans/pro). Bundled so the plugin can
// enrich the model picker, the sidebar panel, and the plan summary tool
// without network access at runtime. Regenerate with `npm run refresh:deals`.

export type PlanId = "go" | "goat" | "pro" | "max" | "max20" | "teampro" | "provider"

export interface DealRates {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
}

export interface PlanInfo {
  price: number
  credits: number
  window5h: number
  windowWeek: number
  /** Human-facing plan name as shown on the Command Code pricing page. */
  display: string
}

export interface ModelDeals {
  /** $/month credit allowance per plan. Absent plan = no data. */
  allowance?: Partial<Record<PlanId, number>>
  /** Deal metadata. endsAt: ISO date or "while capacity lasts". */
  discount?: { pct: number; endsAt?: string }
  /** Pre-deal list prices (for reference). */
  was?: { input: number; output: number; cacheRead: number }
  /** Discounted deal prices (what you pay now). */
  now?: { input: number; output: number; cacheRead: number }
  /** Time-varying rates (DeepSeek V4 peak/off-peak). */
  peakOffPeak?: { peak: DealRates; offPeak: DealRates; windows: string }
  /** Higher-context tier rates (docs: MiniMax M3 >512K). */
  overContext?: DealRates
  benchmark?: { intelligence?: number; tokPerSec?: number }
  tier?: "opensource" | "premium"
  free: boolean
}

export const MODEL_DEALS: Readonly<Record<string, ModelDeals>> = {
  "claude-fable-5": { tier: "premium", benchmark: {"intelligence":62.1,"tokPerSec":67.5}, free: false },
  "claude-haiku-4-5-20251001": { tier: "premium", benchmark: {"intelligence":24.1,"tokPerSec":101.1}, free: false, allowance: {"pro":20} },
  "claude-opus-4-7": { tier: "premium", benchmark: {"intelligence":55}, free: false },
  "claude-opus-4-8": { tier: "premium", benchmark: {"intelligence":57.3}, free: false },
  "claude-opus-5": { tier: "premium", benchmark: {"intelligence":63.1,"tokPerSec":54.4}, free: false },
  "claude-sonnet-4-6": { tier: "premium", benchmark: {"intelligence":48.4}, free: false, allowance: {"pro":20} },
  "claude-sonnet-5": { tier: "premium", benchmark: {"intelligence":55.3,"tokPerSec":81.9}, free: false, allowance: {"pro":20} },
  "deepseek/deepseek-v4-flash": { tier: "opensource", benchmark: {"intelligence":51.8,"tokPerSec":114.6}, peakOffPeak: {"peak":{"input":0.44,"output":1.32,"cacheRead":0.014,"cacheWrite":0},"offPeak":{"input":0.22,"output":0.66,"cacheRead":0.007,"cacheWrite":0},"windows":"01–04 & 06–10 UTC"}, free: false, allowance: {"goat":60,"pro":70} },
  "deepseek/deepseek-v4-pro": { tier: "opensource", benchmark: {"intelligence":53.2,"tokPerSec":75.3}, peakOffPeak: {"peak":{"input":1.32,"output":3.96,"cacheRead":0.044,"cacheWrite":0},"offPeak":{"input":0.66,"output":1.98,"cacheRead":0.022,"cacheWrite":0},"windows":"01–04 & 06–10 UTC"}, free: false, allowance: {"goat":20,"pro":30} },
  "google/gemini-3.1-flash-lite": { tier: "premium", benchmark: {"intelligence":25.6}, free: false, allowance: {"pro":20} },
  "google/gemini-3.5-flash": { tier: "premium", benchmark: {"intelligence":52}, free: false, allowance: {"pro":20} },
  "google/gemini-3.5-flash-lite": { tier: "premium", benchmark: {"intelligence":37.4,"tokPerSec":361.2}, free: false, allowance: {"pro":20} },
  "google/gemini-3.6-flash": { tier: "premium", benchmark: {"intelligence":51.6,"tokPerSec":187.4}, free: false, allowance: {"pro":20} },
  "google/gemini-3.7-flash": { tier: "opensource", discount: {"pct":50,"endsAt":"2026-12-31"}, was: {"input":1.5,"output":7.5,"cacheRead":0.15}, now: {"input":0.75,"output":3.75,"cacheRead":0.075}, benchmark: {"intelligence":56,"tokPerSec":339.4}, free: false, allowance: {"goat":40,"pro":60} },
  "gpt-5.3-codex": { tier: "premium", benchmark: {"intelligence":45.5,"tokPerSec":132.3}, free: false, allowance: {"pro":20} },
  "gpt-5.4": { tier: "premium", benchmark: {"intelligence":53.1}, free: false, allowance: {"pro":20} },
  "gpt-5.4-mini": { tier: "premium", benchmark: {"intelligence":40.9}, free: false, allowance: {"pro":20} },
  "gpt-5.5": { tier: "premium", benchmark: {"intelligence":56.3}, free: false, allowance: {"pro":20} },
  "gpt-5.6-luna": { tier: "opensource", benchmark: {"intelligence":52.3,"tokPerSec":165}, free: false, allowance: {"goat":20,"pro":30} },
  "gpt-5.6-sol": { tier: "opensource", benchmark: {"intelligence":60.9,"tokPerSec":68.7}, free: false, allowance: {"goat":70,"pro":80} },
  "gpt-5.6-terra": { tier: "premium", benchmark: {"intelligence":56.6,"tokPerSec":117.1}, free: false, allowance: {"pro":20} },
  "meta/muse-spark-1.1": { tier: "premium", benchmark: {"intelligence":53.2}, free: false, allowance: {"pro":20} },
  "meta/muse-spark-1.2": { tier: "opensource", benchmark: {"intelligence":56.8}, free: false, allowance: {"goat":20,"pro":30} },
  "meta/muse-spark-1.2-contributor": { tier: "opensource", benchmark: {"intelligence":56.8}, free: false, allowance: {"goat":20,"pro":30} },
  "MiniMaxAI/MiniMax-M2.5": { tier: "opensource", benchmark: {"intelligence":34.5}, free: false },
  "MiniMaxAI/MiniMax-M2.7": { tier: "opensource", benchmark: {"intelligence":38.9}, free: false },
  "MiniMaxAI/MiniMax-M3": { tier: "opensource", discount: {"pct":50}, was: {"input":0.6,"output":2.4,"cacheRead":0.12}, now: {"input":0.3,"output":1.2,"cacheRead":0.06}, benchmark: {"intelligence":45.4,"tokPerSec":104.4}, free: false, allowance: {"goat":47,"pro":57} },
  "moonshotai/Kimi-K2.5": { tier: "opensource", benchmark: {"intelligence":36}, free: false },
  "moonshotai/Kimi-K2.6": { tier: "opensource", benchmark: {"intelligence":45.1}, free: false },
  "moonshotai/Kimi-K2.7-Code": { tier: "opensource", benchmark: {"intelligence":43,"tokPerSec":38.2}, free: false, allowance: {"goat":60,"pro":70} },
  "moonshotai/Kimi-K2.7-Code-Highspeed": { tier: "opensource", free: false, allowance: {"goat":20,"pro":30} },
  "moonshotai/Kimi-K3": { tier: "opensource", benchmark: {"intelligence":59.7,"tokPerSec":38.6}, free: false, allowance: {"goat":20,"pro":30} },
  "nvidia/nemotron-3-ultra-550b-a55b": { tier: "opensource", benchmark: {"intelligence":38.3,"tokPerSec":135.8}, free: false, allowance: {"goat":20,"pro":30} },
  "poolside/laguna-s-2.1-free": { tier: "opensource", free: true },
  "Qwen/Qwen3.6-Max-Preview": { tier: "opensource", benchmark: {"intelligence":41.1}, free: false },
  "Qwen/Qwen3.6-Plus": { tier: "opensource", benchmark: {"intelligence":40.5}, free: false, allowance: {"goat":33,"pro":43} },
  "Qwen/Qwen3.7-Flash": { tier: "opensource", free: false },
  "Qwen/Qwen3.7-Max": { tier: "opensource", benchmark: {"intelligence":46.7}, free: false, allowance: {"goat":33,"pro":43} },
  "Qwen/Qwen3.7-Plus": { tier: "opensource", benchmark: {"intelligence":39.4,"tokPerSec":55.6}, free: false, allowance: {"goat":33,"pro":43} },
  "Qwen/Qwen3.8-27B": { tier: "opensource", benchmark: {"intelligence":52}, free: false, allowance: {"goat":70,"pro":80} },
  "Qwen/Qwen3.8-Max": { tier: "opensource", benchmark: {"intelligence":58.1,"tokPerSec":46.7}, free: false, allowance: {"goat":20,"pro":30} },
  "sakana/fugu-ultra": { tier: "premium", free: false },
  "stepfun/Step-3.5-Flash": { tier: "opensource", benchmark: {"intelligence":26.5}, free: false, allowance: {"goat":20,"pro":30} },
  "stepfun/Step-3.7-Flash": { tier: "opensource", benchmark: {"intelligence":30.9,"tokPerSec":120.1}, free: false, allowance: {"goat":20,"pro":30} },
  "tencent/hy3-paid": { tier: "opensource", benchmark: {"intelligence":42.2,"tokPerSec":74.8}, free: false, allowance: {"goat":70,"pro":80} },
  "thinkingmachines/inkling": { tier: "opensource", benchmark: {"intelligence":42.3,"tokPerSec":69.8}, free: false, allowance: {"goat":20,"pro":30} },
  "thinkingmachines/inkling-small": { tier: "opensource", benchmark: {"intelligence":41.2,"tokPerSec":61.3}, free: false, allowance: {"goat":20,"pro":30} },
  "xai/grok-4.5": { tier: "opensource", benchmark: {"intelligence":55.8,"tokPerSec":51}, free: false, allowance: {"goat":20,"pro":30} },
  "xai/grok-4.6": { tier: "opensource", benchmark: {"intelligence":60.9,"tokPerSec":66}, free: false, allowance: {"goat":20,"pro":30} },
  "xiaomi/mimo-v2.5": { tier: "opensource", discount: {"pct":98}, was: {"input":0.8,"output":4,"cacheRead":0.16}, now: {"input":0.14,"output":0.28,"cacheRead":0.0028}, benchmark: {"intelligence":38,"tokPerSec":61.8}, free: false, allowance: {"goat":30,"pro":40} },
  "xiaomi/mimo-v2.5-pro": { tier: "opensource", discount: {"pct":99}, was: {"input":2,"output":6,"cacheRead":0.4}, now: {"input":0.435,"output":0.87,"cacheRead":0.0036}, benchmark: {"intelligence":42.9,"tokPerSec":58.1}, free: false, allowance: {"goat":20,"pro":30} },
  "zai-org/GLM-5": { tier: "opensource", benchmark: {"intelligence":40.6}, free: false },
  "zai-org/GLM-5.1": { tier: "opensource", benchmark: {"intelligence":41,"tokPerSec":28.2}, free: false },
  "zai-org/GLM-5.2": { tier: "opensource", benchmark: {"intelligence":52.6,"tokPerSec":69}, free: false, allowance: {"goat":70,"pro":80} },
  "zai-org/GLM-5.2-Fast": { tier: "opensource", free: false, allowance: {"goat":20,"pro":30} },
  "zai-org/GLM-5.3": { tier: "opensource", benchmark: {"intelligence":59.5,"tokPerSec":79.6}, free: false, allowance: {"goat":20,"pro":30} },
}

export const PLAN_CATALOG: Readonly<Record<PlanId, PlanInfo>> = {
  go: { price: 1, credits: 10, window5h: 3, windowWeek: 6, display: "Go" },
  goat: { price: 10, credits: 70, window5h: 14, windowWeek: 35, display: "GOAT" },
  pro: { price: 20, credits: 80, window5h: 16, windowWeek: 40, display: "Pro" },
  max: { price: 100, credits: 150, window5h: 45, windowWeek: 90, display: "Max 10×" },
  max20: { price: 200, credits: 300, window5h: 90, windowWeek: 180, display: "Max 20×" },
  teampro: { price: 40, credits: 40, window5h: 12, windowWeek: 24, display: "Team Pro" },
  provider: { price: 15, credits: 0, window5h: 0, windowWeek: 0, display: "Provider" },
}

export const DEAL_SOURCE_URL = "https://commandcode.ai/docs/resources/pricing-limits"
export const DEAL_LAST_REFRESHED = "2026-08-20"
export const DEAL_PACKAGE_VERSION = "docs"
