// src/catalog/deals.ts — GENERATED by scripts/refresh-deals.mjs. Do not edit.
//
// Deal/allowance intelligence parsed from the Command Code docs site
// (pricing-limits, plans/goat, plans/pro, plans/max). Bundled so the plugin
// can enrich the model picker and the plan summary tool without network
// access at runtime. Regenerate with `npm run refresh:deals`.
//
// DEMO: hand-authored sample data. Milestone 1 replaces this file with
// scraper output; the module shape below is the contract the scraper must
// produce.

export type PlanId = "go" | "goat" | "pro" | "max" | "max20" | "provider"

export interface DealRates {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
}

export interface PlanInfo {
  price: number
  credits: number
  window5h: number
  windowWeek: number
}

export interface ModelDeals {
  /** $/month credit allowance per plan. Absent plan = no data. */
  allowance?: Partial<Record<PlanId, number>>
  /** Deal metadata. endsAt: ISO date, "permanent", or "while capacity lasts". */
  discount?: { pct: number; endsAt?: string }
  /** Pre-deal list prices (for reference). */
  was?: { input: number; output: number; cacheRead: number }
  /** Time-varying rates (DeepSeek V4 peak/off-peak). */
  peakOffPeak?: { peak: DealRates; offPeak: DealRates; windows: string }
  /** Higher-context tier rates (docs: MiniMax M3 >512K). */
  overContext?: DealRates
  benchmark?: { intelligence?: number; tokPerSec?: number }
  tier?: "opensource" | "premium"
  free: boolean
}

export const MODEL_DEALS: Readonly<Record<string, ModelDeals>> = {
  "Qwen/Qwen3.8-27B": {
    allowance: { goat: 70 },
    benchmark: { intelligence: 52 },
    tier: "opensource",
    free: false,
  },
  "google/gemini-3.7-flash": {
    allowance: { goat: 40, pro: 60 },
    discount: { pct: 50, endsAt: "2026-12-31" },
    was: { input: 1.5, output: 7.5, cacheRead: 0.15 },
    benchmark: { intelligence: 56, tokPerSec: 339 },
    tier: "premium",
    free: false,
  },
  "MiniMaxAI/MiniMax-M3": {
    allowance: { goat: 47, pro: 57 },
    discount: { pct: 50 },
    was: { input: 0.6, output: 2.4, cacheRead: 0.12 },
    benchmark: { intelligence: 45.4, tokPerSec: 104 },
    tier: "opensource",
    free: false,
  },
  "xiaomi/mimo-v2.5": {
    allowance: { goat: 30, pro: 40 },
    discount: { pct: 98 },
    was: { input: 0.8, output: 4, cacheRead: 0.16 },
    benchmark: { intelligence: 38, tokPerSec: 62 },
    tier: "opensource",
    free: false,
  },
  "xiaomi/mimo-v2.5-pro": {
    allowance: { goat: 20, pro: 30 },
    discount: { pct: 99 },
    was: { input: 2, output: 6, cacheRead: 0.4 },
    benchmark: { intelligence: 42.9, tokPerSec: 58 },
    tier: "opensource",
    free: false,
  },
  "deepseek/deepseek-v4-pro": {
    allowance: { goat: 20 },
    peakOffPeak: {
      peak: { input: 1.32, output: 3.96, cacheRead: 0.044, cacheWrite: 0 },
      offPeak: { input: 0.66, output: 1.98, cacheRead: 0.022, cacheWrite: 0 },
      windows: "01-04 & 06-10 UTC",
    },
    benchmark: { intelligence: 53.2, tokPerSec: 75 },
    tier: "opensource",
    free: false,
  },
  "deepseek/deepseek-v4-flash": {
    allowance: { goat: 60 },
    peakOffPeak: {
      peak: { input: 0.44, output: 1.32, cacheRead: 0.014, cacheWrite: 0 },
      offPeak: { input: 0.22, output: 0.66, cacheRead: 0.007, cacheWrite: 0 },
      windows: "01-04 & 06-10 UTC",
    },
    benchmark: { intelligence: 52, tokPerSec: 115 },
    tier: "opensource",
    free: false,
  },
  "gpt-5.6-sol": {
    allowance: { goat: 70 },
    benchmark: { intelligence: 60.9, tokPerSec: 69 },
    tier: "premium",
    free: false,
  },
  "meta/muse-spark-1.2-contributor": {
    allowance: { goat: 20 },
    benchmark: { intelligence: 56.8 },
    tier: "premium",
    free: false,
  },
  "poolside/laguna-s-2.1-free": {
    tier: "opensource",
    free: true,
  },
}

export const PLAN_CATALOG: Readonly<Record<PlanId, PlanInfo>> = {
  go: { price: 1, credits: 10, window5h: 3, windowWeek: 6 },
  goat: { price: 10, credits: 70, window5h: 14, windowWeek: 35 },
  pro: { price: 20, credits: 80, window5h: 16, windowWeek: 40 },
  max: { price: 100, credits: 150, window5h: 45, windowWeek: 90 },
  max20: { price: 200, credits: 300, window5h: 90, windowWeek: 180 },
  provider: { price: 15, credits: 0, window5h: 0, windowWeek: 0 },
}

export const DEAL_SOURCE_URL = "https://commandcode.ai/docs/resources/pricing-limits"
export const DEAL_LAST_REFRESHED = "2026-08-20"
export const DEAL_PACKAGE_VERSION = "demo"
