// src/catalog/snapshot.ts — GENERATED by scripts/refresh-snapshot.mjs. Do not edit.
//
// A copy of the Command Code model catalog bundled in the package so the
// plugin can auto-register every model without network access at runtime.
// Since issue #130 the npm package models.md table is the sole membership
// authority: every models.md row ships here with its ship-bar fields
// (id, name, context length parsed from the coarse Context column, costs,
// efforts). Since issue #132 a blank models.md cell is resolved through
// the ordered enrichment ladders (context: RSC contextWindow → CLI
// contextWindow → carried-forward; cost: models page index → detail page
// → RSC rates — costs never carry forward), and each row carries its
// `contextSource` / `costSource` provenance. The listing API decides
// nothing and wins no field. Regenerate with `npm run refresh:snapshot`.

export interface CatalogModel {
  readonly id: string
  readonly name: string
  readonly contextLength: number | null
  /** "models.md" when the package cell parsed; else the ladder step that resolved it. */
  readonly contextSource: "models.md" | "rsc" | "cli" | "carried-forward"
  readonly efforts: readonly string[] | null
  readonly cost: {
    readonly input: number
    readonly output: number
    readonly cacheRead: number
    readonly cacheWrite: number
  } | null
  /** "models.md" when the package cell parsed; else the ladder step that resolved it. */
  readonly costSource: "models.md" | "models-page" | "detail" | "rsc"
}

export const MODEL_SNAPSHOT: readonly CatalogModel[] = [
  { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro (latest)", contextLength: 1000000, contextSource: "models.md", efforts: ["high","max"], cost: { input: 0.66, output: 1.98, cacheRead: 0.022, cacheWrite: 0 }, costSource: "models.md" },
  { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash (latest)", contextLength: 1000000, contextSource: "models.md", efforts: ["high","max"], cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 }, costSource: "models.md" },
  { id: "deepseek/deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision (exp)", contextLength: 1000000, contextSource: "models.md", efforts: ["high","max"], cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 }, costSource: "models.md" },
  { id: "deepseek/deepseek-v4-flash-fast", name: "DeepSeek V4 Flash Fast", contextLength: 1000000, contextSource: "models.md", efforts: ["low","high","max"], cost: { input: 0.28, output: 0.56, cacheRead: 0.07, cacheWrite: 0 }, costSource: "models.md" },
  { id: "deepseek/deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash", contextLength: 1000000, contextSource: "models.md", efforts: ["low","high","max"], cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 }, costSource: "models.md" },
  { id: "moonshotai/Kimi-K3", name: "Kimi K3", contextLength: 1000000, contextSource: "models.md", efforts: ["low","high","max"], cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 0 }, costSource: "models.md" },
  { id: "moonshotai/Kimi-K2.7-Code", name: "Kimi K2.7 Code", contextLength: 256000, contextSource: "models.md", efforts: null, cost: { input: 0.95, output: 4, cacheRead: 0.19, cacheWrite: 0 }, costSource: "models.md" },
  { id: "moonshotai/Kimi-K2.7-Code-Highspeed", name: "Kimi K2.7 Code HighSpeed", contextLength: 262000, contextSource: "models.md", efforts: null, cost: { input: 1.9, output: 8, cacheRead: 0.38, cacheWrite: 0 }, costSource: "models.md" },
  { id: "moonshotai/Kimi-K2.6", name: "Kimi K2.6", contextLength: 256000, contextSource: "models.md", efforts: null, cost: { input: 0.95, output: 4, cacheRead: 0.16, cacheWrite: 0 }, costSource: "models.md" },
  { id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5", contextLength: 256000, contextSource: "models.md", efforts: null, cost: { input: 0.6, output: 3, cacheRead: 0.1, cacheWrite: 0 }, costSource: "models.md" },
  { id: "z-ai/glm-5.3-flash", name: "GLM-5.3 Flash", contextLength: 1050000, contextSource: "models.md", efforts: ["low","high","max"], cost: { input: 0.15, output: 0.5, cacheRead: 0.03, cacheWrite: 0 }, costSource: "models.md" },
  { id: "zai-org/GLM-5.3", name: "GLM-5.3", contextLength: 1000000, contextSource: "models.md", efforts: ["low","high","max"], cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 }, costSource: "models.md" },
  { id: "zai-org/GLM-5.2", name: "GLM-5.2", contextLength: 1000000, contextSource: "models.md", efforts: ["high","max"], cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 }, costSource: "models.md" },
  { id: "zai-org/GLM-5.2-Fast", name: "GLM-5.2 Fast", contextLength: 1000000, contextSource: "models.md", efforts: null, cost: { input: 3, output: 10.25, cacheRead: 0.5, cacheWrite: 0 }, costSource: "models.md" },
  { id: "zai-org/GLM-5.1", name: "GLM-5.1", contextLength: 200000, contextSource: "rsc", efforts: null, cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 }, costSource: "models.md" },
  { id: "zai-org/GLM-5", name: "GLM-5", contextLength: 200000, contextSource: "models.md", efforts: null, cost: { input: 1, output: 3.2, cacheRead: 0.2, cacheWrite: 0 }, costSource: "models.md" },
  { id: "MiniMaxAI/MiniMax-M3", name: "MiniMax M3", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high"], cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 }, costSource: "models.md" },
  { id: "MiniMaxAI/MiniMax-M2.7", name: "MiniMax M2.7", contextLength: 200000, contextSource: "rsc", efforts: null, cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 }, costSource: "models.md" },
  { id: "MiniMaxAI/MiniMax-M2.5", name: "MiniMax M2.5", contextLength: 200000, contextSource: "models.md", efforts: null, cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0 }, costSource: "models.md" },
  { id: "xiaomi/mimo-v2.5-pro", name: "MiMo V2.5 Pro", contextLength: 1000000, contextSource: "models.md", efforts: null, cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 }, costSource: "models.md" },
  { id: "xiaomi/mimo-v2.5", name: "MiMo V2.5", contextLength: 1000000, contextSource: "models.md", efforts: null, cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 }, costSource: "models.md" },
  { id: "Qwen/Qwen3.8-Max-0902", name: "Qwen 3.8 Max 0902", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","xhigh"], cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 0 }, costSource: "models.md" },
  { id: "Qwen/Qwen3.8-Max", name: "Qwen 3.8 Max", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","xhigh"], cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 2.5 }, costSource: "models.md" },
  { id: "Qwen/Qwen3.8-27B", name: "Qwen 3.8 27B", contextLength: 262000, contextSource: "models.md", efforts: ["low","medium","xhigh"], cost: { input: 0.4, output: 3, cacheRead: 0.04, cacheWrite: 0 }, costSource: "models.md" },
  { id: "Qwen/Qwen3.8-Flash", name: "Qwen 3.8 Flash", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","xhigh"], cost: { input: 0.16, output: 0.47, cacheRead: 0.016, cacheWrite: 0 }, costSource: "models.md" },
  { id: "Qwen/Qwen3.7-Max", name: "Qwen 3.7 Max", contextLength: 1000000, contextSource: "models.md", efforts: null, cost: { input: 2.5, output: 7.5, cacheRead: 0.5, cacheWrite: 3.13 }, costSource: "models.md" },
  { id: "Qwen/Qwen3.7-Plus", name: "Qwen 3.7 Plus", contextLength: 1000000, contextSource: "models.md", efforts: null, cost: { input: 0.4, output: 1.6, cacheRead: 0.08, cacheWrite: 0.5 }, costSource: "models.md" },
  { id: "Qwen/Qwen3.7-Flash", name: "Qwen 3.7 Flash", contextLength: 1000000, contextSource: "models.md", efforts: null, cost: { input: 0.03, output: 0.13, cacheRead: 0.006, cacheWrite: 0.038 }, costSource: "models.md" },
  { id: "Qwen/Qwen3.6-Max-Preview", name: "Qwen 3.6 Max Preview", contextLength: 200000, contextSource: "rsc", efforts: null, cost: { input: 1.3, output: 7.8, cacheRead: 0.26, cacheWrite: 1.63 }, costSource: "models.md" },
  { id: "Qwen/Qwen3.6-Plus", name: "Qwen 3.6 Plus", contextLength: 200000, contextSource: "rsc", efforts: null, cost: { input: 0.5, output: 3, cacheRead: 0.1, cacheWrite: 0 }, costSource: "models.md" },
  { id: "meituan/LongCat-2.0:free", name: "LongCat 2.0", contextLength: 1050000, contextSource: "models.md", efforts: null, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, costSource: "models.md" },
  { id: "stepfun/Step-3.7-Flash", name: "Step 3.7 Flash", contextLength: 256000, contextSource: "models.md", efforts: null, cost: { input: 0.2, output: 1.15, cacheRead: 0.04, cacheWrite: 0 }, costSource: "models.md" },
  { id: "stepfun/Step-3.5-Flash", name: "Step 3.5 Flash", contextLength: 1000000, contextSource: "models.md", efforts: null, cost: { input: 0.1, output: 0.3, cacheRead: 0.02, cacheWrite: 0 }, costSource: "models.md" },
  { id: "tencent/hy3-paid", name: "Tencent Hy3", contextLength: 262000, contextSource: "models.md", efforts: null, cost: { input: 0.14, output: 0.58, cacheRead: 0.035, cacheWrite: 0 }, costSource: "models.md" },
  { id: "tencent/hy4-preview", name: "Tencent Hy4 Preview", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high"], cost: { input: 0.834, output: 2.501, cacheRead: 0.042, cacheWrite: 0 }, costSource: "models.md" },
  { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra", contextLength: 1000000, contextSource: "models.md", efforts: null, cost: { input: 0.6, output: 2.4, cacheRead: 0.12, cacheWrite: 0 }, costSource: "models.md" },
  { id: "thinkingmachines/inkling", name: "Inkling", contextLength: 256000, contextSource: "models.md", efforts: null, cost: { input: 1, output: 4.05, cacheRead: 0.17, cacheWrite: 0 }, costSource: "models.md" },
  { id: "thinkingmachines/inkling-small", name: "Inkling Small", contextLength: 1000000, contextSource: "models.md", efforts: null, cost: { input: 0.5, output: 1.2, cacheRead: 0.1, cacheWrite: 0 }, costSource: "models.md" },
  { id: "poolside/laguna-s-2.1-free", name: "Laguna S 2.1", contextLength: 256000, contextSource: "models.md", efforts: null, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, costSource: "models.md" },
  { id: "inclusionai/ling-3.0-flash-sante:free", name: "Ling 3.0 Flash Sante", contextLength: 262000, contextSource: "models.md", efforts: null, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, costSource: "models.md" },
  { id: "claude-sonnet-5", name: "Claude Sonnet 5", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 }, costSource: "models.md" },
  { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 }, costSource: "models.md" },
  { id: "claude-fable-5-1", name: "Claude Fable 5.1", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 10, output: 50, cacheRead: 0.25, cacheWrite: 12.5 }, costSource: "models.md" },
  { id: "claude-fable-5", name: "Claude Fable 5", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 }, costSource: "models.md" },
  { id: "claude-opus-5", name: "Claude Opus 5", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 }, costSource: "models.md" },
  { id: "claude-opus-4-8", name: "Claude Opus 4.8", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 }, costSource: "models.md" },
  { id: "claude-opus-4-7", name: "Claude Opus 4.7", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 }, costSource: "models.md" },
  { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5", contextLength: 200000, contextSource: "models.md", efforts: null, cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 }, costSource: "models.md" },
  { id: "gpt-6-astra", name: "GPT-6 Astra", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 }, costSource: "models.md" },
  { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 }, costSource: "models.md" },
  { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 2.5 }, costSource: "models.md" },
  { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 0.2, output: 1.2, cacheRead: 0.02, cacheWrite: 0.25 }, costSource: "models.md" },
  { id: "gpt-5.5", name: "GPT-5.5", contextLength: 400000, contextSource: "models.md", efforts: ["low","medium","high","xhigh"], cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 }, costSource: "models.md" },
  { id: "gpt-5.4", name: "GPT-5.4", contextLength: 400000, contextSource: "models.md", efforts: ["low","medium","high","xhigh"], cost: { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 0 }, costSource: "models.md" },
  { id: "gpt-5.3-codex", name: "GPT-5.3 Codex", contextLength: 400000, contextSource: "models.md", efforts: ["low","medium","high","xhigh"], cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 }, costSource: "models.md" },
  { id: "gpt-5.4-mini", name: "GPT-5.4 Mini", contextLength: 400000, contextSource: "models.md", efforts: ["low","medium","high"], cost: { input: 0.75, output: 4.5, cacheRead: 0.075, cacheWrite: 0 }, costSource: "models.md" },
  { id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high"], cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 }, costSource: "models.md" },
  { id: "google/gemini-3.7-flash", name: "Gemini 3.7 Flash", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high"], cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0.08334 }, costSource: "models.md" },
  { id: "google/gemini-3.6-flash", name: "Gemini 3.6 Flash", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high"], cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 }, costSource: "models.md" },
  { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high"], cost: { input: 1.5, output: 9, cacheRead: 0.15, cacheWrite: 0 }, costSource: "models.md" },
  { id: "google/gemini-3.5-flash-lite", name: "Gemini 3.5 Flash Lite", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high"], cost: { input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0 }, costSource: "models.md" },
  { id: "google/gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite", contextLength: 1000000, contextSource: "models.md", efforts: ["low","medium","high"], cost: { input: 0.25, output: 1.5, cacheRead: 0.03, cacheWrite: 0 }, costSource: "models.md" },
  { id: "sakana/fugu-ultra", name: "Fugu Ultra", contextLength: 1000000, contextSource: "models.md", efforts: ["high","xhigh"], cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 }, costSource: "models.md" },
  { id: "meta/muse-spark-1.1", name: "Muse Spark 1.1", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high","xhigh"], cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 }, costSource: "models.md" },
  { id: "meta/muse-spark-1.2", name: "Muse Spark 1.2", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high","xhigh"], cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 }, costSource: "models.md" },
  { id: "meta/muse-spark-1.2-contributor", name: "Muse Spark 1.2 Contributor", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high","xhigh"], cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 }, costSource: "models.md" },
  { id: "meta/muse-spark-1.3", name: "Muse Spark 1.3", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high","xhigh","max"], cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 }, costSource: "models.md" },
  { id: "meta/muse-spark-1.3-contributor", name: "Muse Spark 1.3 Contributor", contextLength: 1050000, contextSource: "models.md", efforts: ["low","medium","high","xhigh"], cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 }, costSource: "models.md" },
  { id: "xai/grok-4.5", name: "Grok 4.5", contextLength: 500000, contextSource: "models.md", efforts: ["low","medium","high"], cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 }, costSource: "models.md" },
  { id: "xai/grok-4.6", name: "Grok 4.6", contextLength: 500000, contextSource: "models.md", efforts: ["low","medium","high","xhigh"], cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 }, costSource: "models.md" },
]
