// tests/auto-release.test.ts — seam: the auto-release flow (issue #115).
// Merging a catalog-refresh PR cuts a patch release: version bump, lockfile
// sync, a CHANGELOG section authored from the merged PR body's semantic
// sections, a bot-authored `chore(release): X.Y.Z` commit on main, and a
// `vX.Y.Z` tag — which triggers the unchanged tag-driven release pipeline
// (one publish path, ADR-0002).
//
// Per the repo's cron-workflow test pattern, the bump/commit/tag shell
// fragment is spawned against a synthetic repository (local bare remote
// standing in for origin), and the CHANGELOG authoring is exercised as a
// pure module over a synthetic PR body. The merged PR body is untrusted
// upstream-derived input: it travels env → file → module (read as data),
// never interpolated into run scripts.
import { execFile } from "node:child_process"
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { promisify } from "node:util"
import { buildChangelogSection } from "../scripts/release-notes.mjs"
import { assert, assertEqual, run } from "./harness.js"

const exec = promisify(execFile)

const TODAY = new Date().toISOString().split("T")[0]

// A synthetic refresh PR body with the exact section shape the cron's
// "Build PR body from catalog diff" step produces.
const PR_BODY = [
  "## Catalog refresh — 2026-09-03",
  "",
  "Automated refresh of the generated catalog files. Review the file-level diff below before merging.",
  "",
  "### Changed files",
  "",
  "```",
  " src/catalog/classification.ts | 4 ++--",
  "```",
  "",
  "### Model catalog",
  "",
  "## Model catalog",
  "",
  "- **FACTS_LAST_REFRESHED**: `2026-09-01` → `2026-09-03`",
  "",
  "| Model                        | Change  | Before | After                 |",
  "| ---------------------------- | ------- | ------ | --------------------- |",
  "| `gpt-5.6-sol`                | added   | —      | GPT-5.6 Sol · 400000 ctx |",
  "",
  "### Reasoning classification",
  "",
  "## Reasoning classification",
  "",
  "- **CLASSIFICATION_LAST_REFRESHED**: `2026-09-01` → `2026-09-03`",
  "",
  "| Model               | Change         | Before                   | After                                    |",
  "| ------------------- | -------------- | ------------------------ | ---------------------------------------- |",
  "| `moonshotai/Kimi-K3` | classification | reasoning-without-efforts | efforts model (low, high, max)          |",
  "",
  "### Deals intelligence",
  "",
  "## Deals intelligence",
  "",
  "- **DEAL_LAST_REFRESHED**: `2026-09-01` → `2026-09-03`",
  "No changes.",
  "",
  "---",
  "",
  "_Auto-generated by the `catalog-refresh` workflow. Review and merge._",
  "",
].join("\n")

// The exact release fragments the auto-release workflow runs (the
// "Cut the patch release" and "Push main and the tag" steps, concatenated;
// see `.github/workflows/auto-release.yml`). Update this copy in the same
// commit as any workflow change — a divergence means the workflow is no
// longer locked by the test. The body arrives as the file `pr-body.md`
// (never interpolated into this script); version and tag are computed
// locally from package.json. The tag-existence rail is a FULL skip: the
// bump step reports skip=true and the push step is gated on that output
// (SKIP_PUSH=1 stands in for the workflow's step-level `if`).
const RELEASE_FRAGMENT = `
  set -euo pipefail
  version="$(node -p "require('./package.json').version")"
  next="$(node -e "const [maj,min,pat]=process.argv[1].split('.').map(Number);process.stdout.write(maj+'.'+min+'.'+(pat+1))" "$version")"
  if git rev-parse -q --verify "refs/tags/v\${next}" >/dev/null; then
    echo "::warning::tag v\${next} already exists — skipping the auto-release (no commit, no tag, no push)."
    echo "skip=true"
    exit 0
  fi
  echo "skip=false"
  date="$(date -u +%Y-%m-%d)"
  node scripts/release-notes.mjs "\${next}" "\${date}" pr-body.md > release-notes.md
  { cat release-notes.md; cat CHANGELOG.md; } > CHANGELOG.md.new
  mv CHANGELOG.md.new CHANGELOG.md
  npm version "\${next}" --no-git-tag-version --allow-same-version >/dev/null
  npm install --package-lock-only >/dev/null 2>&1
  git config user.name "github-actions[bot]"
  git config user.email "github-actions[bot]@users.noreply.github.com"
  git add package.json package-lock.json CHANGELOG.md
  git commit -q -m "chore(release): \${next}"
  git tag "v\${next}"
  if [ "\${SKIP_PUSH:-0}" != "1" ]; then
    next="$(node -p "require('./package.json').version")"
    git push -q origin main "v\${next}"
    echo "auto-release: cut v\${next} on main; the tag-driven release pipeline takes it from here."
  fi
`

interface Repo {
  work: string
  cleanup: () => Promise<void>
}

async function setupRepo({ tag = false } = {}): Promise<Repo> {
  const base = await mkdtemp(join(tmpdir(), "cc-auto-release-"))
  const remote = join(base, "remote.git")
  const work = join(base, "work")
  await exec("git", ["init", "--bare", "-q", remote])
  await exec("git", ["init", "-q", "-b", "main", work])
  await exec("git", ["-C", work, "config", "user.email", "test@example.com"])
  await exec("git", ["-C", work, "config", "user.name", "Test"])
  await exec("git", ["-C", work, "config", "commit.gpgsign", "false"])
  await exec("git", ["-C", work, "remote", "add", "origin", remote])
  await writeFile(
    join(work, "package.json"),
    JSON.stringify({ name: "synthetic-pkg", version: "1.6.2" }, null, 2) + "\n",
    "utf-8",
  )
  await writeFile(
    join(work, "CHANGELOG.md"),
    ["## 1.6.2 - 2026-08-01", "", "- previous release.", "", ""].join("\n"),
    "utf-8",
  )
  await writeFile(join(work, "pr-body.md"), PR_BODY, "utf-8")
  // The workflow runs the repo's own release-notes script; copy the real
  // one so the fragment runs exactly what CI runs.
  await exec("mkdir", ["-p", join(work, "scripts")])
  await cp(
    join(process.cwd(), "scripts", "release-notes.mjs"),
    join(work, "scripts", "release-notes.mjs"),
  )
  await exec("git", ["-C", work, "add", "-A"])
  await exec("git", ["-C", work, "commit", "-q", "-m", "seed"])
  await exec("git", ["-C", work, "push", "-q", "origin", "main"])
  if (tag) {
    await exec("git", ["-C", work, "tag", "v1.6.3"])
    await exec("git", ["-C", work, "push", "-q", "origin", "v1.6.3"])
  }
  return {
    work,
    cleanup: async () => await rm(base, { recursive: true, force: true }),
  }
}

async function runReleaseFragment(
  work: string,
  env: Record<string, string> = {},
): Promise<{ code: number; out: string }> {
  try {
    const { stdout } = await exec("bash", ["-c", RELEASE_FRAGMENT], {
      cwd: work,
      env: { ...process.env, npm_config_cache: join(tmpdir(), "cc-npm-cache"), ...env },
    })
    return { code: 0, out: stdout }
  } catch (error) {
    const err = error as { code?: number; stdout?: string; stderr?: string }
    return { code: err.code ?? 1, out: `${err.stdout ?? ""}${err.stderr ?? ""}` }
  }
}

run([
  [
    "buildChangelogSection: authors the CHANGELOG section from the PR body's semantic sections",
    () => {
      const section = buildChangelogSection({
        version: "1.6.3",
        date: "2026-09-03",
        prBody: PR_BODY,
      })
      // The section heading in the format the release pipeline's changelog
      // extraction expects (`^## X.Y.Z - date`).
      assert(section.startsWith("## 1.6.3 - 2026-09-03"), section.slice(0, 80))
      // Semantic sections render with their change tables.
      assert(section.includes("### Model catalog"), section)
      assert(section.includes("### Reasoning classification"), section)
      // The added model renders as a table row.
      assert(
        section.split("\n").some((line) => {
          if (!line.trimStart().startsWith("|")) return false
          const cells = line
            .split("|")
            .slice(1, -1)
            .map((c) => c.trim())
          return cells[0] === "`gpt-5.6-sol`" && cells[1] === "added"
        }),
        section,
      )
      // The classification flip renders as a table row.
      assert(
        section.split("\n").some((line) => {
          if (!line.trimStart().startsWith("|")) return false
          const cells = line
            .split("|")
            .slice(1, -1)
            .map((c) => c.trim())
          return (
            cells[0] === "`moonshotai/Kimi-K3`" &&
            cells[1] === "classification" &&
            cells[2] === "reasoning-without-efforts" &&
            cells[3] === "efforts model (low, high, max)"
          )
        }),
        section,
      )
      // The Deals section carried only the date line + "No changes." — no
      // change rows, so it is dropped from the release notes (the 1.6.3
      // release note bug: bare empty headings in the CHANGELOG).
      assert(!section.includes("### Deals intelligence"), section)
      // The Changed-files block and the bot footer are NOT semantic — out.
      assert(!section.includes("Changed files"), section)
      assert(!section.includes("Auto-generated by"), section)
      assert(!section.includes("src/catalog/classification.ts | 4"), section)
      // Deterministic: same inputs → same bytes.
      assertEqual(
        section,
        buildChangelogSection({ version: "1.6.3", date: "2026-09-03", prBody: PR_BODY }),
      )
    },
  ],
  [
    "buildChangelogSection: degrades gracefully when the PR body has no semantic sections",
    () => {
      const section = buildChangelogSection({
        version: "1.6.3",
        date: "2026-09-03",
        prBody: "unparseable body with no sections",
      })
      assert(section.startsWith("## 1.6.3 - 2026-09-03"), section)
      assert(!section.includes("###"), section)
    },
  ],
  [
    "release fragment: merging a refresh PR cuts the bot-authored patch release",
    async () => {
      const repo = await setupRepo()
      try {
        const result = await runReleaseFragment(repo.work)
        assertEqual(result.code, 0, result.out)
        // Version bumped.
        const pkg = JSON.parse(await readFile(join(repo.work, "package.json"), "utf-8")) as {
          version: string
        }
        assertEqual(pkg.version, "1.6.3")
        // Lockfile synced via npm (never hand-edited).
        const lock = JSON.parse(await readFile(join(repo.work, "package-lock.json"), "utf-8")) as {
          version: string
          packages?: Record<string, { version?: string }>
        }
        assertEqual(lock.version, "1.6.3")
        assertEqual(lock.packages?.[""]?.version, "1.6.3")
        // CHANGELOG section authored from the PR body's semantic sections.
        const changelog = await readFile(join(repo.work, "CHANGELOG.md"), "utf-8")
        assert(
          changelog.startsWith(`## 1.6.3 - ${TODAY}`),
          `expected the new section first, got: ${changelog.slice(0, 80)}`,
        )
        assert(
          changelog.split("\n").some((line) => {
            if (!line.trimStart().startsWith("|")) return false
            const cells = line
              .split("|")
              .slice(1, -1)
              .map((c) => c.trim())
            return (
              cells[0] === "`moonshotai/Kimi-K3`" &&
              cells[1] === "classification" &&
              cells[2] === "reasoning-without-efforts" &&
              cells[3] === "efforts model (low, high, max)"
            )
          }),
          changelog,
        )
        assert(!changelog.includes("Changed files"), changelog)
        assert(changelog.includes("## 1.6.2 - 2026-08-01"), "the old section must survive")
        // Bot-authored bump commit on main, tagged.
        const { stdout: subject } = await exec("git", ["-C", repo.work, "log", "-1", "--format=%s"])
        assertEqual(subject.trim(), "chore(release): 1.6.3")
        const { stdout: author } = await exec("git", ["-C", repo.work, "log", "-1", "--format=%an"])
        assertEqual(author.trim(), "github-actions[bot]")
        const { stdout: tagTarget } = await exec("git", [
          "-C",
          repo.work,
          "rev-parse",
          "v1.6.3^{commit}",
        ])
        const { stdout: head } = await exec("git", ["-C", repo.work, "rev-parse", "HEAD"])
        assertEqual(tagTarget.trim(), head.trim(), "the tag must point at the bump commit")
        // Pushed: main and the tag are on the remote (the release pipeline
        // runs from the tag; its on-main assertion needs the commit on main).
        const { stdout: refs } = await exec("git", ["-C", repo.work, "ls-remote", "origin"])
        assert(refs.includes("refs/heads/main"), refs)
        assert(refs.includes("refs/tags/v1.6.3"), refs)
      } finally {
        await repo.cleanup()
      }
    },
  ],
  [
    "release fragment: a pre-existing vX.Y.Z tag causes a full skip (no commit, no tag, no push)",
    async () => {
      const repo = await setupRepo({ tag: true })
      try {
        const result = await runReleaseFragment(repo.work)
        assertEqual(result.code, 0, result.out)
        assert(
          result.out.includes("skipping the auto-release"),
          `expected a loud skip, got: ${result.out}`,
        )
        // The bump step reports skip=true — the workflow's push step is
        // gated on exactly this output (`steps.release.outputs.skip !=
        // 'true'`, locked statically below).
        assert(result.out.includes("skip=true"), `expected skip=true, got: ${result.out}`)
        const pkg = JSON.parse(await readFile(join(repo.work, "package.json"), "utf-8")) as {
          version: string
        }
        assertEqual(pkg.version, "1.6.2", "the version must not move on a tag skip")
        const { stdout: subject } = await exec("git", ["-C", repo.work, "log", "-1", "--format=%s"])
        assertEqual(subject.trim(), "seed", "no release commit may be created")
        const changelog = await readFile(join(repo.work, "CHANGELOG.md"), "utf-8")
        assert(!changelog.includes("## 1.6.3"), "no CHANGELOG section may be added")
        // The push step must not run after the skip: gated fragment is a
        // no-op (the workflow's step-level `if` skips the step outright).
        const gated = await runReleaseFragment(repo.work, { SKIP_PUSH: "1" })
        assertEqual(gated.code, 0, gated.out)
        assert(
          !gated.out.includes("the tag-driven release pipeline takes it from here"),
          `the push step must be skipped after a tag skip, got: ${gated.out}`,
        )
      } finally {
        await repo.cleanup()
      }
    },
  ],
  [
    "the auto-release workflow guards: merged + catalog-refresh branch + skip-release label",
    async () => {
      // The job-level `if:` is a GitHub expression — not spawnable — so the
      // guard is locked statically: a future edit that drops any of the
      // three rails fails here.
      const workflow = await readFile(
        join(process.cwd(), ".github/workflows/auto-release.yml"),
        "utf-8",
      )
      assert(workflow.includes("github.event.pull_request.merged == true"), workflow)
      assert(
        workflow.includes("startsWith(github.event.pull_request.head.ref, 'catalog-refresh/')"),
        workflow,
      )
      assert(workflow.includes("skip-release"), workflow)
      // Concurrency-serialized (safety rail).
      assert(workflow.includes("concurrency:"), workflow)
      // The checkout must NOT persist the default token credential: it
      // would override the push token (run 33683416448 failed exactly
      // this way — push ran as github-actions[bot] and was rule-rejected).
      assert(
        workflow.includes("persist-credentials: false"),
        "checkout must set persist-credentials: false so the push uses RELEASE_PUSH_TOKEN",
      )
      // The push step must clear any inherited credential header before
      // rewriting the remote URL (defence in depth).
      assert(
        workflow.includes("git config --unset-all http.https://github.com/.extraheader"),
        "the push step must clear the inherited extraheader before pushing",
      )
      // The tag-existence rail must gate the PUSH step too — a full skip
      // means no commit, no tag, and no push.
      assert(
        workflow.includes("if: steps.release.outputs.skip != 'true'"),
        "the push step must be gated on the bump step's skip output",
      )
      assert(workflow.includes('echo "skip=true" >> "$GITHUB_OUTPUT"'), workflow)
      // The body must travel as a file/env, never spliced into `run:`.
      assert(
        !workflow.includes("${{ github.event.pull_request.body }}") || workflow.includes("PR_BODY"),
        workflow,
      )
    },
  ],
])
