// tests/catalog-refresh-drift.test.ts — seam: the `Detect drift against
// main` step in `.github/workflows/catalog-refresh.yml` (issue #113).
//
// The cron's drift check used to be a raw byte-diff over the generated
// modules AND the RSC fixtures. That opened no-op PRs: a run where
// nothing upstream changed still produced a PR whose only diff was the
// refreshed-date stamps (PR #103 is exactly this), and fixture bytes
// churn with upstream site deploys (build-id hashes) even when the data
// is identical. The fix judges **meaningful** drift: only the generated
// catalog modules, with the release gate's established date-stamp
// ignores (the refreshed-date lines of the facts, deals, and
// classification modules) — the same convention ADR-0003's release gate
// uses, so the cron and the release gate agree on what counts as "no
// change". Movements of the facts source/package-version lines remain
// meaningful (they signal a real upstream package event). Fixtures keep
// riding along in meaningful refresh commits but no longer decide drift.
//
// Per the repo's cron-workflow test pattern, this test spawns the exact
// shell fragment the workflow runs, against synthetic before/after git
// trees. It also documents the original failure mode: the pre-fix
// fragment (no date-stamp ignores) reports drift on date-only churn —
// the sensitivity check that keeps the ignores from being dropped.
import { execFile } from "node:child_process"
import { mkdtemp, rm, writeFile, mkdir } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { promisify } from "node:util"
import { assert, assertEqual, run } from "./harness.js"

const exec = promisify(execFile)

// The exact drift-check fragment the workflow runs (see the
// `Detect meaningful drift against main` step in
// `.github/workflows/catalog-refresh.yml`). If the workflow's fragment
// changes, update this copy in the same commit — a divergence here means
// the workflow is no longer locked by the test.
const DRIFT_FRAGMENT = `
  git fetch origin main
  if git diff --quiet \
      -I 'FACTS_LAST_REFRESHED' \
      -I 'DEAL_LAST_REFRESHED' \
      -I 'CLASSIFICATION_LAST_REFRESHED' \
      origin/main -- \\
      src/catalog/snapshot.ts \\
      src/catalog/facts.ts \\
      src/catalog/classification.ts \\
      src/deals/catalog.ts; then
    echo "drift=false"
  else
    echo "drift=true"
    git diff --stat \\
      -I 'FACTS_LAST_REFRESHED' \\
      -I 'DEAL_LAST_REFRESHED' \\
      -I 'CLASSIFICATION_LAST_REFRESHED' \\
      origin/main -- \\
      src/catalog/snapshot.ts \\
      src/catalog/facts.ts \\
      src/catalog/classification.ts \\
      src/deals/catalog.ts
  fi
`

// The pre-fix fragment: a raw byte-diff including the fixture files —
// exactly what opened no-op PR #103. Kept as the negative control.
const PREFIX_FRAGMENT = `
  git fetch origin main
  if git diff --quiet origin/main -- \\
      src/catalog/snapshot.ts \\
      src/catalog/facts.ts \\
      src/catalog/classification.ts \\
      src/deals/catalog.ts \\
      tests/fixtures/rsc-pricing-limits.txt \\
      tests/fixtures/rsc-goat.txt \\
      tests/fixtures/rsc-pro.txt; then
    echo "drift=false"
  else
    echo "drift=true"
  fi
`

const GENERATED_FILES = {
  "src/catalog/snapshot.ts": [
    "// src/catalog/snapshot.ts — GENERATED by scripts/refresh-snapshot.mjs. Do not edit.",
    "",
    "export const MODEL_SNAPSHOT: Readonly<Record<string, unknown>> = {",
    '  "claude-sonnet-5": { name: "Claude Sonnet 5", contextLength: 200000 },',
    '  "moonshotai/Kimi-K3": { name: "Kimi K3", contextLength: 256000 },',
    "}",
    "",
  ],
  "src/catalog/facts.ts": [
    "// src/catalog/facts.ts — GENERATED by scripts/refresh-snapshot.mjs. Do not edit.",
    "",
    'export const FACTS_SOURCE_URL = "https://unpkg.com/command-code@1.39.2/dist/bundled/command-code-knowledge/reference/models.md"',
    'export const FACTS_PACKAGE_VERSION = "1.39.2"',
    'export const FACTS_LAST_REFRESHED = "2026-09-01"',
    "",
    "export const MODEL_EFFORTS: Readonly<Record<string, readonly string[]>> = {",
    '  "claude-sonnet-5": ["low", "medium", "high"],',
    "}",
    "",
  ],
  "src/catalog/classification.ts": [
    "// src/catalog/classification.ts — GENERATED by scripts/refresh-classification.mjs. Do not edit.",
    "",
    'export const CLASSIFICATION_LAST_REFRESHED = "2026-09-01"',
    "",
    "export const MODEL_REASONING_CAPABILITY: Readonly<Record<string, boolean>> = {",
    '  "claude-sonnet-5": true,',
    '  "moonshotai/Kimi-K3": true,',
    "}",
    "",
  ],
  "src/deals/catalog.ts": [
    "// src/deals/catalog.ts — GENERATED by scripts/refresh-deals.mjs. Do not edit.",
    "",
    "export const MODEL_DEALS: Readonly<Record<string, unknown>> = {",
    '  "claude-sonnet-5": { tier: "premium", free: false },',
    "}",
    "",
    'export const DEAL_LAST_REFRESHED = "2026-09-01"',
    'export const DEAL_PACKAGE_VERSION = "docs"',
    "",
  ],
  "tests/fixtures/rsc-goat.txt": [
    '2:[{"slug":"kimi-k3","id":"moonshotai/Kimi-K3","build":"aaa"}]',
    "",
  ],
  "tests/fixtures/rsc-pro.txt": [
    '2:[{"slug":"kimi-k3","id":"moonshotai/Kimi-K3","build":"aaa"}]',
    "",
  ],
  "tests/fixtures/rsc-pricing-limits.txt": ['2:[{"id":"kimi-k3","build":"aaa"}]', ""],
}

interface Repo {
  work: string
  cleanup: () => Promise<void>
}

async function setupRepo(): Promise<Repo> {
  const base = await mkdtemp(join(tmpdir(), "cc-cron-drift-"))
  const remote = join(base, "remote.git")
  const work = join(base, "work")
  await exec("git", ["init", "--bare", "-q", remote])
  await exec("git", ["init", "-q", "-b", "main", work])
  await exec("git", ["-C", work, "config", "user.email", "test@example.com"])
  await exec("git", ["-C", work, "config", "user.name", "Test"])
  await exec("git", ["-C", work, "config", "commit.gpgsign", "false"])
  await exec("git", ["-C", work, "remote", "add", "origin", remote])
  for (const [path, lines] of Object.entries(GENERATED_FILES)) {
    await mkdir(join(work, path, ".."), { recursive: true })
    await writeFile(join(work, path), lines.join("\n"), "utf-8")
  }
  await exec("git", ["-C", work, "add", "-A"])
  await exec("git", ["-C", work, "commit", "-q", "-m", "seed generated catalogs"])
  await exec("git", ["-C", work, "push", "-q", "origin", "main"])
  return {
    work,
    cleanup: async () => await rm(base, { recursive: true, force: true }),
  }
}

async function runFragment(fragment: string, work: string): Promise<{ code: number; out: string }> {
  try {
    const { stdout } = await exec("bash", ["-c", fragment], { cwd: work })
    return { code: 0, out: stdout }
  } catch (error) {
    const err = error as { code?: number; stdout?: string }
    return { code: err.code ?? 1, out: err.stdout ?? "" }
  }
}

/** Applies a mutation to the working tree (the "after" cron state). */
async function mutate(work: string, path: string, lines: string[]): Promise<void> {
  await mkdir(join(work, path, ".."), { recursive: true })
  await writeFile(join(work, path), lines.join("\n"), "utf-8")
}

/** Returns the file lines with every line matching `match` replaced. */
function withLineReplaced(lines: string[], match: string | RegExp, replacement: string): string[] {
  return lines.map((line) =>
    typeof match === "string"
      ? line === match
        ? replacement
        : line
      : match.test(line)
        ? replacement
        : line,
  )
}

run([
  [
    "drift: a date-only-churn run with churned fixtures opens no PR (the #103 replay ships nothing)",
    async () => {
      const repo = await setupRepo()
      try {
        // The nothing-changed run: every generated module identical
        // except the refreshed-date stamps, fixture bytes churned
        // (upstream site deploy → new build ids).
        await mutate(
          repo.work,
          "src/catalog/facts.ts",
          withLineReplaced(
            GENERATED_FILES["src/catalog/facts.ts"],
            /^export const FACTS_LAST_REFRESHED/,
            'export const FACTS_LAST_REFRESHED = "2026-09-02"',
          ),
        )
        await mutate(
          repo.work,
          "src/catalog/classification.ts",
          withLineReplaced(
            GENERATED_FILES["src/catalog/classification.ts"],
            /^export const CLASSIFICATION_LAST_REFRESHED/,
            'export const CLASSIFICATION_LAST_REFRESHED = "2026-09-02"',
          ),
        )
        await mutate(
          repo.work,
          "src/deals/catalog.ts",
          withLineReplaced(
            GENERATED_FILES["src/deals/catalog.ts"],
            /^export const DEAL_LAST_REFRESHED/,
            'export const DEAL_LAST_REFRESHED = "2026-09-02"',
          ),
        )
        await mutate(repo.work, "tests/fixtures/rsc-goat.txt", [
          '2:[{"slug":"kimi-k3","id":"moonshotai/Kimi-K3","build":"bbb-churned"}]',
          "",
        ])
        const post = await runFragment(DRIFT_FRAGMENT, repo.work)
        assertEqual(post.code, 0)
        assert(
          post.out.includes("drift=false"),
          `date-only churn must not count as drift, got: ${post.out}`,
        )
        // Sensitivity check: the pre-fix raw byte-diff WOULD have opened
        // the no-op PR #103 produced. If this ever stops holding, the
        // ignores have stopped doing their job.
        const pre = await runFragment(PREFIX_FRAGMENT, repo.work)
        assert(
          pre.out.includes("drift=true"),
          "the pre-fix fragment must report drift on date-only churn (documents the bug)",
        )
      } finally {
        await repo.cleanup()
      }
    },
  ],
  [
    "drift: a real data change in any generated module still opens the refresh PR",
    async () => {
      const repo = await setupRepo()
      try {
        // A capability value moves (the same date stamps otherwise).
        await mutate(
          repo.work,
          "src/catalog/classification.ts",
          withLineReplaced(
            withLineReplaced(
              GENERATED_FILES["src/catalog/classification.ts"],
              /^export const CLASSIFICATION_LAST_REFRESHED/,
              'export const CLASSIFICATION_LAST_REFRESHED = "2026-09-02"',
            ),
            '  "moonshotai/Kimi-K3": true,',
            '  "moonshotai/Kimi-K3": false,',
          ),
        )
        const post = await runFragment(DRIFT_FRAGMENT, repo.work)
        // The step signals drift through $GITHUB_OUTPUT, not its exit
        // code (the if/else's last command is `git diff --stat`, which
        // exits 0 on both branches).
        assert(
          post.out.includes("drift=true"),
          `a real classification change must count as drift, got: ${post.out}`,
        )
      } finally {
        await repo.cleanup()
      }
    },
  ],
  [
    "drift: a facts source/package-version line move still counts as drift",
    async () => {
      const repo = await setupRepo()
      try {
        // A real upstream package event: the facts source URL and
        // package version move to a new command-code release.
        await mutate(
          repo.work,
          "src/catalog/facts.ts",
          withLineReplaced(
            withLineReplaced(
              GENERATED_FILES["src/catalog/facts.ts"],
              /^export const FACTS_SOURCE_URL/,
              'export const FACTS_SOURCE_URL = "https://unpkg.com/command-code@1.40.0/dist/bundled/command-code-knowledge/reference/models.md"',
            ),
            /^export const FACTS_PACKAGE_VERSION/,
            'export const FACTS_PACKAGE_VERSION = "1.40.0"',
          ),
        )
        const post = await runFragment(DRIFT_FRAGMENT, repo.work)
        assert(
          post.out.includes("drift=true"),
          `a facts package-version move must count as drift, got: ${post.out}`,
        )
      } finally {
        await repo.cleanup()
      }
    },
  ],
  [
    "drift: fixture-only changes never open a PR",
    async () => {
      const repo = await setupRepo()
      try {
        // Only the fixture bytes churn; the generated modules are
        // byte-identical to main.
        await mutate(repo.work, "tests/fixtures/rsc-pro.txt", [
          '2:[{"slug":"kimi-k3","id":"moonshotai/Kimi-K3","build":"ccc-deploy"}]',
          "",
        ])
        const post = await runFragment(DRIFT_FRAGMENT, repo.work)
        assertEqual(post.code, 0)
        assert(
          post.out.includes("drift=false"),
          `fixture-only churn must not open a PR, got: ${post.out}`,
        )
      } finally {
        await repo.cleanup()
      }
    },
  ],
])
