// tests/catalog-metadata.test.ts — catalog-wide metadata coverage (issue #22).
//
// Capability facts (reasoning efforts + per-1M-token rates) come from
// `src/catalog/facts.ts`, generated from the command-code npm package's
// bundled models.md (see FACTS_SOURCE_URL / FACTS_PACKAGE_VERSION in that
// file). These tests guarantee every snapshot model resolves capability + cost
// metadata instead of silently falling back to text-only / no-reasoning /
// zero-cost. Reasoning classification is **derived** from the generated
// classification module (`src/catalog/classification.ts`, the docs RSC
// records' reasoning flag) combined with the generated efforts facts —
// there is no hand-maintained classification set and no advisory
// non-reasoning list (issue #111, ADR-0006); modalities are generated from
// the CLI bundle's inputModalities fields.
//
// **Self-sustainability note (catalog-refresh cron, issue #89).** The
// `EFFORTS_MODELS` test set is **auto-derived from `MODEL_EFFORTS`**
// (the generated catalog facts) — the npm package's models.md is the
// source of truth for which models expose effort levels, and the
// facts are regenerated on every cron run. When Command Code adds a
// new model with explicit efforts (e.g. deepseek/deepseek-v4-flash-fast
// on 2026-08-31), it lands in `MODEL_EFFORTS` on the next refresh and
// the reasoning-classification test follows automatically; no human
// pin update required.
import { MODEL_SNAPSHOT } from "../src/catalog/snapshot.js"
import { MODEL_INPUT_MODALITIES, inputModalitiesForModel } from "../src/provider/modalities.js"
import { MODEL_EFFORTS, REASONING_MODELS, isReasoningModel } from "../src/provider/reasoning.js"
import { MODEL_COSTS } from "../src/provider/pricing.js"
import { MODEL_DEALS } from "../src/deals/catalog.js"
import { assert, assertEqual, run } from "./harness.js"

// The free-variant set is **derived from the generated Deals catalog's
// free flag** (spec #108, user story 7) — a retired free variant can no
// longer go stale and break the suite, and a free model the docs newly
// mark is picked up automatically. The Deals catalog is generated by
// `npm run refresh:deals` from the docs' RSC records.
const FREE_MODELS = new Set(
  Object.entries(MODEL_DEALS)
    .filter(([, deal]) => deal.free === true)
    .map(([id]) => id),
)

// EFFORTS_MODELS is auto-derived from the generated `MODEL_EFFORTS` so
// the test tracks upstream package changes without a manual pin
// update. The npm package's models.md is the source of truth for
// which models expose effort levels; the catalog-refresh cron
// regenerates the facts on every run.
const EFFORTS_MODELS = new Set(Object.keys(MODEL_EFFORTS))

run([
  [
    "every snapshot model has a cost entry (or is free)",
    () => {
      for (const model of MODEL_SNAPSHOT) {
        const costs = MODEL_COSTS[model.id]
        if (FREE_MODELS.has(model.id)) {
          assert(costs && costs.input === 0 && costs.output === 0, model.id)
          continue
        }
        assert(costs, `missing cost for ${model.id}`)
        assert(costs.input > 0 || costs.output > 0, `zero-cost entry for ${model.id}`)
      }
    },
  ],

  [
    "muse-spark pricing is covered by the synthetic parser fixture, not pinned here",
    () => {
      // Upstream *values* moved to tests/parse-facts.test.ts over the
      // synthetic models.md fixture (spec #108 story 8): a real upstream
      // price change must surface as a refresh-PR diff, never as a red
      // test. Here only the relation is asserted: the ids used to be pinned
      // stay resolvable from the generated facts as long as upstream lists
      // them.
      for (const id of [
        "meta/muse-spark-1.2-contributor",
        "meta/muse-spark-1.1",
        "meta/muse-spark-1.2",
      ]) {
        if (!MODEL_SNAPSHOT.some((model) => model.id === id)) continue
        const costs = MODEL_COSTS[id]
        assert(costs, `${id} must keep a generated cost entry while upstream lists it`)
        assert(
          costs.input > 0 && costs.output > 0,
          `${id} is a paid model; a zero entry would mean a parsing regression`,
        )
      }
    },
  ],

  [
    "generated modality facts advertise image input and keep text fallback",
    () => {
      for (const model of MODEL_SNAPSHOT) {
        const modalities = inputModalitiesForModel(model.id)
        assertEqual(
          modalities.includes("text"),
          true,
          `${model.id}: expected text input, got ${JSON.stringify(modalities)}`,
        )
        assert(modalities.every((modality) => modality === "text" || modality === "image"))
      }
      assertEqual(inputModalitiesForModel("Qwen/Qwen3.8-27B"), ["text", "image"])
      assertEqual(inputModalitiesForModel("google/gemini-3.7-flash"), ["text", "image"])
      assertEqual(inputModalitiesForModel("xai/grok-4.6"), ["text"])
    },
  ],

  [
    "MODEL_INPUT_MODALITIES has no stale entries outside the snapshot",
    () => {
      const snapshotIds = new Set(MODEL_SNAPSHOT.map((model) => model.id))
      for (const id of Object.keys(MODEL_INPUT_MODALITIES)) {
        assert(snapshotIds.has(id), `${id} is not in the snapshot`)
      }
    },
  ],

  [
    "MODEL_COSTS has no stale entries outside the snapshot",
    () => {
      const snapshotIds = new Set(MODEL_SNAPSHOT.map((model) => model.id))
      for (const id of Object.keys(MODEL_COSTS)) {
        assert(snapshotIds.has(id), `${id} is not in the snapshot`)
      }
    },
  ],

  [
    "reasoning classification is derived from the generated module (efforts precedence by construction)",
    () => {
      // The classification contract since issue #111 (spec #108):
      //   - in MODEL_EFFORTS (generated facts) → "efforts" model;
      //   - capability flag true AND no efforts entry (the derived
      //     REASONING_MODELS set) → "reasoning without efforts" model;
      //   - otherwise → non-reasoning.
      // The "a model is classified exactly once" invariant holds by
      // construction (efforts precedence inside the derivation), so this
      // is a wiring/derivation check over the real generated data — not a
      // post-regeneration cron gate, and not an upstream value pin.
      for (const model of MODEL_SNAPSHOT) {
        const hasEfforts = EFFORTS_MODELS.has(model.id)
        const reasoningWithoutEfforts = REASONING_MODELS.has(model.id)
        assert(
          !(hasEfforts && reasoningWithoutEfforts),
          `${model.id}: efforts precedence violated — an efforts model must never be in the derived reasoning-without-efforts set`,
        )
        // isReasoningModel must agree with the union of MODEL_EFFORTS +
        // the derived REASONING_MODELS (the same union the src-side
        // isReasoningModel computes).
        assertEqual(isReasoningModel(model.id), hasEfforts || reasoningWithoutEfforts, model.id)
      }
    },
  ],

  [
    "efforts metadata is structurally valid (the spec-example pin asserts structure, not literal values)",
    () => {
      // The old `tencent/hy4-preview is an efforts model` pin literally
      // asserted upstream's efforts list — an upstream value change broke
      // the suite and blocked the cron. The spec-example pin is now
      // structural: non-empty arrays of known effort levels only.
      const KNOWN_LEVELS = new Set(["minimal", "low", "medium", "high", "xhigh", "max"])
      for (const [id, efforts] of Object.entries(MODEL_EFFORTS)) {
        assert(efforts.length > 0, `${id}: efforts entry must be non-empty`)
        for (const effort of efforts) {
          assert(KNOWN_LEVELS.has(effort), `${id}: unknown effort level ${effort}`)
        }
      }
    },
  ],

  [
    "no reasoning entry references a model outside the snapshot",
    () => {
      // The generated MODEL_EFFORTS facts and the derived
      // REASONING_MODELS set are the only places a snapshot model is
      // "named as reasoning-capable" — they must stay in sync with the
      // snapshot (the classification structural test regenerates the
      // module itself; this catches a facts/derivation wiring drift).
      const snapshotIds = new Set(MODEL_SNAPSHOT.map((model) => model.id))
      for (const id of Object.keys(MODEL_EFFORTS)) {
        assert(snapshotIds.has(id), `${id} is not in the snapshot (MODEL_EFFORTS stale)`)
      }
      for (const id of REASONING_MODELS) {
        assert(snapshotIds.has(id), `${id} is not in the snapshot (REASONING_MODELS stale)`)
      }
    },
  ],
])
