// tests/classification.test.ts — structural consistency over the **real**
// regenerated classification module (issue #110). This is the release-time
// staleness gate: when the Snapshot gains a model and the classification
// module was not regenerated, `npm test` fails loudly here — no cron or
// release-pipeline change required.
import { readFileSync } from "node:fs"
import { MODEL_SNAPSHOT } from "../src/catalog/snapshot.js"
import {
  CLASSIFICATION_OVERRIDES,
  MODEL_REASONING_CAPABILITY,
} from "../src/catalog/classification.js"
import {
  CLASSIFICATION_OVERRIDES as overridesSource,
  validateClassificationOverrides,
} from "../scripts/classification-overrides.mjs"
import { assert, assertEqual, run } from "./harness.js"

const MODULE_TEXT = readFileSync(
  new URL("../src/catalog/classification.ts", import.meta.url),
  "utf-8",
)

run([
  [
    "every Snapshot model has a classification entry (release-time staleness gate)",
    () => {
      const missing = MODEL_SNAPSHOT.filter(
        (model) => typeof MODEL_REASONING_CAPABILITY[model.id] !== "boolean",
      )
      assertEqual(
        missing.map((model) => model.id),
        [] as string[],
        `classification module is stale — regenerate with \`npm run refresh\` (or \`npm run refresh:classification -- --fixtures\`)`,
      )
    },
  ],
  [
    "classification has no entries outside the Snapshot (no stale derived ids)",
    () => {
      const snapshotIds = new Set(MODEL_SNAPSHOT.map((model) => model.id))
      const stale = Object.keys(MODEL_REASONING_CAPABILITY).filter((id) => !snapshotIds.has(id))
      assertEqual(stale, [] as string[], "stale classification entries must be regenerated away")
    },
  ],
  [
    "the generated module carries the GENERATED do-not-edit header",
    () => {
      assert(
        MODULE_TEXT.includes("GENERATED by scripts/refresh-classification.mjs"),
        "missing generated header",
      )
      assert(MODULE_TEXT.includes("Do not edit"), "missing do-not-edit marker")
    },
  ],
  [
    "the embedded overrides match the override source and validate cleanly",
    () => {
      // The generated module embeds the active overrides; if the source
      // map moved and the module was not regenerated, this fails.
      assertEqual(CLASSIFICATION_OVERRIDES, overridesSource)
      validateClassificationOverrides(CLASSIFICATION_OVERRIDES)
    },
  ],
])
