// tests/classification.test.ts — structural consistency over the **real**
// regenerated classification module (issue #110). This is the release-time
// staleness gate: when the Snapshot gains a model and the classification
// module was not regenerated, `npm test` fails loudly here — no cron or
// release-pipeline change required.
import { readFileSync } from "node:fs"
import { MODEL_SNAPSHOT } from "../src/catalog/snapshot.js"
import {
  CLASSIFICATION_OVERRIDES,
  MODEL_REASONING_CAPABILITY,
  MODEL_REASONING_PENDING,
} from "../src/catalog/classification.js"
import {
  CLASSIFICATION_OVERRIDES as overridesSource,
  validateClassificationOverrides,
} from "../scripts/classification-overrides.mjs"
import { assert, assertEqual, run } from "./harness.js"

const MODULE_TEXT = readFileSync(
  new URL("../src/catalog/classification.ts", import.meta.url),
  "utf-8",
)

run([
  [
    "every Snapshot model is either classified or listed as pending (sparse map, issue #132)",
    () => {
      // Issue #132: the capability map is sparse — only models with
      // evidence (efforts / RSC flag / page Reasoning bit) get an entry.
      // A model with NO evidence must be listed in MODEL_REASONING_PENDING
      // (never silently absent). This is the release-time staleness gate:
      // when the Snapshot gains a model and classification was not
      // regenerated, npm test fails loudly here.
      const snapshotIds = new Set(MODEL_SNAPSHOT.map((model) => model.id))
      const pending = new Set(MODEL_REASONING_PENDING)
      const classified = new Set(Object.keys(MODEL_REASONING_CAPABILITY))
      const missing = MODEL_SNAPSHOT.filter(
        (model) => !classified.has(model.id) && !pending.has(model.id),
      ).map((model) => model.id)
      assertEqual(
        missing,
        [] as string[],
        `classification module is stale — every snapshot model must be classified or pending; ` +
          `regenerate with \`npm run refresh\` (or \`npm run refresh:classification -- --fixtures\`)`,
      )
    },
  ],
  [
    "classification has no entries or pending ids outside the Snapshot (no stale derived ids)",
    () => {
      const snapshotIds = new Set(MODEL_SNAPSHOT.map((model) => model.id))
      const stale = Object.keys(MODEL_REASONING_CAPABILITY).filter((id) => !snapshotIds.has(id))
      assertEqual(stale, [] as string[], "stale classification entries must be regenerated away")
      const stalePending = MODEL_REASONING_PENDING.filter((id) => !snapshotIds.has(id))
      assertEqual(
        stalePending,
        [] as string[],
        "stale pending ids must be regenerated away (pending is a snapshot subset)",
      )
    },
  ],
  [
    "the generated module carries the GENERATED do-not-edit header",
    () => {
      assert(
        MODULE_TEXT.includes("GENERATED by scripts/refresh-classification.mjs"),
        "missing generated header",
      )
      assert(MODULE_TEXT.includes("Do not edit"), "missing do-not-edit marker")
    },
  ],
  [
    "the embedded overrides match the override source and validate cleanly",
    () => {
      // The generated module embeds the active overrides; if the source
      // map moved and the module was not regenerated, this fails.
      assertEqual(CLASSIFICATION_OVERRIDES, overridesSource)
      validateClassificationOverrides(CLASSIFICATION_OVERRIDES)
    },
  ],
])
