// tests/ladders.test.ts — issue #132 skew matrix, end-to-end through the
// mock Command Code server. The refresh ladders must resolve every
// enrichment gap the same way the real pipeline does, with provenance and
// never a silent default. Synthetic worlds only (never upstream's current
// values): value moves must surface as refresh PR diffs, not red tests.
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join, dirname } from "node:path"
import { spawn } from "node:child_process"
import { startMockCc } from "./helpers/mock-cc.js"
import { assert, assertEqual, run } from "./harness.js"

function runScript(args, env) {
  return new Promise((resolve, reject) => {
    const child = spawn("node", args, { env, stdio: ["ignore", "pipe", "pipe"] })
    let stdout = ""
    let stderr = ""
    child.stdout.on("data", (c) => (stdout += c))
    child.stderr.on("data", (c) => (stderr += c))
    child.on("error", reject)
    child.on("close", (status) => resolve({ status, stdout, stderr }))
  })
}

const MODELS_MD = (rows) =>
  "## Open Source\n\n" +
  "| Id | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
  "|---|---|---|---|---|---|---|\n" +
  rows.join("\n") +
  "\n"

const API_UNLISTED = { object: "list", data: [] }
const REGISTRY = { "dist-tags": { latest: "9.9.9" } }

const MODEL_A = "vendor/day1-with-efforts"
const MODEL_B = "vendor/no-evidence"
const MODEL_C = "vendor/missing-ctx"
const MODEL_D = "vendor/missing-price"

/**
 * Runs one snapshot refresh against a fully-synthetic upstream world.
 * Returns the process result + the emitted snapshot rows (via the module
 * text, so the test asserts on the ladder *output*, not internals).
 */
async function refreshSnapshot({ md, cli, rscGoat, rscPro, detail }, assertLkg = true) {
  const dir = await mkdtemp(join(tmpdir(), "cc-ladders-"))
  const out = join(dir, "snapshot.ts")
  const factsOut = join(dir, "facts.ts")
  // Seed the previous snapshot for the carried-forward leg (issue #132
  // context ladder): MODEL_B had 400000 last time.
  if (assertLkg) {
    await mkdir(dirname(out), { recursive: true })
    await writeFile(
      out,
      "// GENERATED by scripts/refresh-snapshot.mjs\n" +
        "export interface CatalogModel { id: string; name: string; contextLength: number | null; efforts: readonly string[] | null; cost: { input: number; output: number; cacheRead: number; cacheWrite: number } | null }\n" +
        "export const MODEL_SNAPSHOT = [\n" +
        '  { id: "vendor/no-evidence", name: "No Evidence", contextLength: 400000, efforts: null, cost: null },\n' +
        "]\n",
      "utf-8",
    )
  }
  const mock = await startMockCc({
    models: API_UNLISTED,
    registry: REGISTRY,
    factsMd: MODELS_MD(md),
    modalitiesBundle:
      cli ??
      `const models = { U: { id: "vendor/unrelated", name: "U", inputModalities: ["text"], contextWindow: 1e6 } }`,
    rscGoat: rscGoat ?? "",
    rscPro: rscPro ?? "",
    modelDetailPages: detail ?? {},
  })
  const env = {
    ...process.env,
    COMMANDCODE_API_BASE: mock.url,
    COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
    COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
    COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
    COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
    COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
    COMMANDCODE_MODELS_PAGE_URL: `${mock.url}/models-page.html`,
    COMMANDCODE_MODELS_DETAIL_URL: `${mock.url}/model-detail`,
  }
  try {
    const result = await runScript(
      ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
      env,
    )
    let rows = []
    let factsText = ""
    // The emitted snapshot is a .ts module; parse it with tsx (the same
    // mechanism the cron's extract step uses) so assertions read real rows.
    try {
      const mod = (await import(/* @vite-ignore */ out)) as {
        MODEL_SNAPSHOT?: Array<Record<string, unknown>>
      }
      rows = (mod.MODEL_SNAPSHOT ?? []) as Array<Record<string, unknown>>
    } catch {
      rows = []
    }
    try {
      factsText = await readFile(factsOut, "utf-8")
    } catch {
      factsText = ""
    }
    return { result, rows, factsText, dir }
  } finally {
    await mock.close()
  }
}

run([
  [
    "skew: a day-1 model with efforts but no API/RSC record ships reasoning-with-efforts (any-true via models.md)",
    async () => {
      const { result, rows, factsText, dir } = await refreshSnapshot({
        md: [
          `| \`${MODEL_A}\` | Day One | 1M | low, medium, high | $2/$10 · cache $0.2 | Go | best |`,
        ],
        cli: `const models = { A: { id: "${MODEL_A}", name: "Day One", inputModalities: ["text"], contextWindow: 1e6 } }`,
        rscGoat: `2:${JSON.stringify([{ slug: "day1", id: MODEL_A, name: "Day One", vendor: "vendor", category: "opensource", minPlanName: "Go", tiers: [], caps: {}, reasoning: false }])}\n`,
        rscPro: "",
      })
      assertEqual(result.status, 0, result.stderr || result.stdout)
      const row = rows.find((r) => r.id === MODEL_A)
      assert(row, "day-1 model must ship")
      assertEqual(row.contextLength, 1000000)
      assertEqual(row.cost.input, 2)
      // Any-true classification: efforts from models.md (see
      // refresh-classification), so it advertises reasoning with variants.
      assert(factsText.includes('"low","medium","high"'), "efforts must reach the facts shim")
      await rm(dir, { recursive: true, force: true })
    },
  ],

  [
    "skew: a no-evidence model ships core-only with the classification-pending bucket and text fallback",
    async () => {
      const { result, rows, factsText, dir } = await refreshSnapshot({
        // No RSC record, no efforts, no page evidence for MODEL_B; its
        // models.md Context cell is missing too, so the context ladder
        // walks RSC (absent) → CLI (absent) → carried-forward LKG (400000).
        md: [`| \`${MODEL_B}\` | No Evidence | — | — | $2/$10 · cache $0.2 | Go | best |`],
        rscGoat: "",
        rscPro: "",
      })
      assertEqual(result.status, 0, result.stderr || result.stdout)
      const row = rows.find((r) => r.id === MODEL_B)
      assert(row, "no-evidence model must ship")
      // Carried-forward LKG resolves its context (previous snapshot had
      // 400000) with provenance.
      assertEqual(row.contextLength, 400000)
      assertEqual(row.contextSource, "carried-forward")
      // Text fallback: no image entry in MODEL_INPUT_MODALITIES (the
      // runtime falls back to ["text"]), even though the row has costs.
      const modSection = factsText.slice(factsText.indexOf("MODEL_INPUT_MODALITIES"))
      assert(
        !modSection.includes(MODEL_B),
        "no-evidence model must not appear in MODEL_INPUT_MODALITIES (text fallback)",
      )
      await rm(dir, { recursive: true, force: true })
    },
  ],

  [
    "skew: total cost-ladder absence fails loudly (never carry-forward, never zero-fill)",
    async () => {
      // With no models page / detail / RSC rates configured, a missing
      // price row is unshippable after the full ladder → loud failure
      // naming it (and stating costs never carry forward). A previous
      // snapshot with a cost for the same row must NOT be used.
      const { result, dir } = await refreshSnapshot({
        md: [`| \`${MODEL_B}\` | No Evidence | 1M | — | — | Go | best |`],
        rscGoat: "",
        rscPro: "",
      })
      assert(result.status !== 0, "a price row with no rates anywhere must fail loudly")
      assert(
        result.stderr.includes(MODEL_B) &&
          /no cost after the full fallback ladder/.test(result.stderr),
        `expected loud cost failure naming the row, got: ${result.stderr}`,
      )
      assert(
        /costs never carry forward/i.test(result.stderr),
        "the failure must state that costs never carry forward (the LKG seed had no cost either way)",
      )
      await rm(dir, { recursive: true, force: true })
    },
  ],

  [
    "skew: cost ladder resolves via the models page row with provenance when rates exist there",
    async () => {
      // gpt-5-4's models.md row has a missing price cell ("—"); the models
      // page index serves its rates, so the cost ladder resolves at the
      // models-page step with provenance. (Synthetic rate values on a real
      // slug — the page row never decides membership.)
      const MODEL = "gpt-5.4"
      const modelsPage =
        `<table><thead><tr><th>Model</th><th>Context</th><th>Intelligence</th><th>Tok/s</th><th>Input</th><th>Output</th><th>Cache read</th><th>Cache write</th><th>Caps</th></tr></thead><tbody>` +
        `<tr><td><a href="/models/gpt-5-4">GPT-5.4</a></td><td><span>1M</span></td><td>52</td><td>—</td><td><span>$7</span></td><td><span>$14</span></td><td><span>$0.7</span></td><td><span>—</span></td><td><button type="button" aria-label="Capabilities: Text input"></button></td></tr>` +
        `</tbody></table>`
      const dir = await mkdtemp(join(tmpdir(), "cc-ladders2-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: API_UNLISTED,
        registry: REGISTRY,
        factsMd: MODELS_MD([`| \`${MODEL}\` | GPT-5.4 | 1M | — | — | Go | best |`]),
        modalitiesBundle: `const models = { U: { id: "vendor/unrelated", name: "U", inputModalities: ["text"], contextWindow: 1e6 } }`,
        rscGoat: "",
        rscPro: "",
        modelsPageHtml: modelsPage,
      })
      const env = {
        ...process.env,
        COMMANDCODE_API_BASE: mock.url,
        COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
        COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
        COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
        COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
        COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        COMMANDCODE_MODELS_PAGE_URL: `${mock.url}/models-page.html`,
        COMMANDCODE_MODELS_DETAIL_URL: `${mock.url}/model-detail`,
      }
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          env,
        )
        assertEqual(result.status, 0, result.stderr || result.stdout)
        const mod = (await import(out)) as { MODEL_SNAPSHOT?: Array<Record<string, unknown>> }
        const row = (mod.MODEL_SNAPSHOT ?? []).find((r) => r.id === MODEL)
        assert(row, "the missing-price row must ship")
        assertEqual(row.costSource, "models-page")
        assertEqual(row.cost, { input: 7, output: 14, cacheRead: 0.7, cacheWrite: 0 })
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "skew: explicit all-zero stays free (picker suffix and sidebar agreement), missing never reads as free",
    async () => {
      const FREE = "vendor/free-model"
      const dir = await mkdtemp(join(tmpdir(), "cc-ladders3-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: API_UNLISTED,
        registry: REGISTRY,
        factsMd: MODELS_MD([
          `| \`${FREE}\` | Free Model | 256K | — | $0/$0 · cache $0 | Go | best |`,
          `| \`${MODEL_C}\` | Missing Ctx | — | — | $1/$2 · cache $0.1 | Go | best |`,
        ]),
        modalitiesBundle: `const models = { F: { id: "${FREE}", name: "Free", inputModalities: ["text"], contextWindow: 256e3 } }`,
        rscGoat: `2:${JSON.stringify([{ slug: "mctx", id: MODEL_C, name: "Missing Ctx", vendor: "vendor", category: "opensource", minPlanName: "Go", contextWindow: 33000, tiers: [], caps: {}, reasoning: false }])}\n`,
        rscPro: "",
      })
      const env = {
        ...process.env,
        COMMANDCODE_API_BASE: mock.url,
        COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
        COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
        COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
        COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
        COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        COMMANDCODE_MODELS_PAGE_URL: `${mock.url}/models-page.html`,
        COMMANDCODE_MODELS_DETAIL_URL: `${mock.url}/model-detail`,
      }
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          env,
        )
        assertEqual(result.status, 0, result.stderr || result.stdout)
        const text = await readFile(out, "utf-8")
        const freeRow = text.split("\n").find((l) => l.includes(FREE))
        assert(
          freeRow.includes("input: 0"),
          `explicit all-zero must parse to free, got: ${freeRow}`,
        )
        const ctxRow = text.split("\n").find((l) => l.includes(MODEL_C))
        assert(ctxRow.includes("contextLength: 33000"), `RSC context must resolve, got: ${ctxRow}`)
        assert(ctxRow.includes('contextSource: "rsc"'), `RSC provenance missing, got: ${ctxRow}`)
        // Sidebar (deals) agreement: the deals generator marks free models.
        const factsText = await readFile(factsOut, "utf-8")
        assert(
          factsText.includes(`"${FREE}": { input: 0, output: 0`),
          `free model must carry all-zero facts, got: ${factsText.slice(0, 200)}`,
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "skew: cost ladder resolves via the model detail page header with provenance when no models-page row exists",
    async () => {
      // gpt-5.4's models.md row has a missing price and the models page
      // index does NOT carry the row; the detail page (/model-detail/...)
      // does, so the ladder resolves at the detail step with provenance.
      // Detail pages are live-fetch-only by design (issue #129) — the mock
      // serves one on demand.
      const MODEL = "gpt-5.4"
      const detailPage =
        `<div class="grid grid-cols-2 rail-2 rail-lg-noleft">` +
        `<div class="border-b border-border/60 px-5 py-[18px] odd:border-r odd:border-border/60"><div class="flex items-center gap-1.5 font-mono text-[10px] tracking-[0.1em] uppercase text-muted-foreground">Input<button type="button" aria-label="Input — Price per 1M input (prompt) tokens." class="relative flex size-[15px] cursor-help items-center justify-center border border-border text-[11px] leading-none text-muted-foreground/70 transition-colors hover:text-foreground focus:outline-none focus-visible:text-foreground focus-visible:ring-1 focus-visible:ring-current after:absolute after:-inset-[14.5px] after:content-[&#x27;&#x27;]" data-state="closed">i</button></div><div class="mt-1 text-[21px] font-semibold tabular-nums">$3.5<!-- --> <span class="text-xs font-normal text-muted-foreground/70">/M</span></div></div>` +
        `<div class="border-b border-border/60 px-5 py-[18px] odd:border-r odd:border-border/60"><div class="flex items-center gap-1.5 font-mono text-[10px] tracking-[0.1em] uppercase text-muted-foreground">Output<button type="button" aria-label="Output — Price per 1M output (generated) tokens." class="relative flex size-[15px] cursor-help items-center justify-center border border-border text-[11px] leading-none text-muted-foreground/70 transition-colors hover:text-foreground focus:outline-none focus-visible:text-foreground focus-visible:ring-1 focus-visible:ring-current after:absolute after:-inset-[14.5px] after:content-[&#x27;&#x27;]" data-state="closed">i</button></div><div class="mt-1 text-[21px] font-semibold tabular-nums">$14<!-- --> <span class="text-xs font-normal text-muted-foreground/70">/M</span></div></div>` +
        `<div class="border-b border-border/60 px-5 py-[18px] odd:border-r odd:border-border/60"><div class="flex items-center gap-1.5 font-mono text-[10px] tracking-[0.1em] uppercase text-muted-foreground">Cache read<button type="button" aria-label="Cache read — Price per 1M cached input tokens re-read from context — far cheaper than fresh input." class="relative flex size-[15px] cursor-help items-center justify-center border border-border text-[11px] leading-none text-muted-foreground/70 transition-colors hover:text-foreground focus:outline-none focus-visible:text-foreground focus-visible:ring-1 focus-visible:ring-current after:absolute after:-inset-[14.5px] after:content-[&#x27;&#x27;]" data-state="closed">i</button></div><div class="mt-1 text-[21px] font-semibold tabular-nums">$0.35<!-- --> <span class="text-xs font-normal text-muted-foreground/70">/M</span></div></div>` +
        `</div>`
      const dir = await mkdtemp(join(tmpdir(), "cc-ladders-detail-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: API_UNLISTED,
        registry: REGISTRY,
        factsMd: MODELS_MD([`| \`${MODEL}\` | GPT-5.4 | 1M | — | — | Go | best |`]),
        modalitiesBundle: `const models = { U: { id: "vendor/unrelated", name: "U", inputModalities: ["text"], contextWindow: 1e6 } }`,
        rscGoat: "",
        rscPro: "",
        modelDetailPages: { "gpt-5.4": detailPage },
      })
      const env = {
        ...process.env,
        COMMANDCODE_API_BASE: mock.url,
        COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
        COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
        COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
        COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
        COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        COMMANDCODE_MODELS_PAGE_URL: `${mock.url}/models-page.html`,
        COMMANDCODE_MODELS_DETAIL_URL: `${mock.url}/model-detail`,
      }
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          env,
        )
        assertEqual(result.status, 0, result.stderr || result.stdout)
        const mod = (await import(out)) as { MODEL_SNAPSHOT?: Array<Record<string, unknown>> }
        const row = (mod.MODEL_SNAPSHOT ?? []).find((r) => r.id === MODEL)
        assert(row, "the missing-price row must ship via the detail page")
        assertEqual(row.costSource, "detail")
        assertEqual(row.cost, { input: 3.5, output: 14, cacheRead: 0.35, cacheWrite: 0 })
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "skew: cost ladder resolves via RSC slug-record rates (costSource rsc) when page and detail are absent",
    async () => {
      // A model with a missing models.md price, no models-page row, and a
      // detail page that carries no pricing (all-null parse) falls through
      // to the RSC slug-record rates. cacheWrite "$undefined" resolves to 0.
      const MODEL = "gpt-5.4"
      const slugRecord = {
        slug: "gpt-5-4",
        id: MODEL,
        name: "GPT-5.4",
        vendor: "openai",
        category: "premium",
        minPlanName: "Pro",
        inputCost: 9,
        outputCost: 45,
        cacheReadCost: 0.9,
        cacheWriteCost: "$undefined",
        tiers: [],
        caps: {},
        reasoning: true,
      }
      // The RSC parser's slug-records predicate requires the FIRST record
      // id to be vendor-prefixed (contains "/"); put a prefixed filler
      // first so the gpt-5.4 record is recognized.
      const filler = {
        slug: "deepseek-v4-flash",
        id: "deepseek/deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        vendor: "deepseek",
        category: "opensource",
        minPlanName: "Go",
        inputCost: 1,
        outputCost: 2,
        cacheReadCost: 0.1,
        cacheWriteCost: 0,
        tiers: [],
        caps: {},
        reasoning: true,
      }
      const dir = await mkdtemp(join(tmpdir(), "cc-ladders-rsc-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: API_UNLISTED,
        registry: REGISTRY,
        factsMd: MODELS_MD([`| \`${MODEL}\` | GPT-5.4 | 1M | — | — | Go | best |`]),
        modalitiesBundle: `const models = { U: { id: "vendor/unrelated", name: "U", inputModalities: ["text"], contextWindow: 1e6 } }`,
        rscGoat: `2:${JSON.stringify([filler, slugRecord])}\n`,
        rscPro: "",
      })
      const env = {
        ...process.env,
        COMMANDCODE_API_BASE: mock.url,
        COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
        COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
        COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
        COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
        COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        COMMANDCODE_MODELS_PAGE_URL: `${mock.url}/models-page.html`,
        COMMANDCODE_MODELS_DETAIL_URL: `${mock.url}/model-detail`,
      }
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          env,
        )
        assertEqual(result.status, 0, result.stderr || result.stdout)
        const mod = (await import(out)) as { MODEL_SNAPSHOT?: Array<Record<string, unknown>> }
        const row = (mod.MODEL_SNAPSHOT ?? []).find((r) => r.id === MODEL)
        assert(row, "the missing-price row must ship via RSC rates")
        assertEqual(row.costSource, "rsc")
        assertEqual(row.cost, { input: 9, output: 45, cacheRead: 0.9, cacheWrite: 0 })
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "skew: a CLI-omitted model with a models-page Caps Vision bit promotes to image with provenance",
    async () => {
      // The modalities ladder: CLI omits the model, but the models page
      // Caps Vision bit is set → MODEL_INPUT_MODALITIES gains a text+image
      // entry (the runtime advertises image input).
      const MODEL = "gpt-5.4"
      const modelsPage =
        `<table><thead><tr><th>Model</th><th>Context</th><th>Intelligence</th><th>Tok/s</th><th>Input</th><th>Output</th><th>Cache read</th><th>Cache write</th><th>Caps</th></tr></thead><tbody>` +
        `<tr><td><a href="/models/gpt-5-4">GPT-5.4</a></td><td><span>1M</span></td><td>52</td><td>—</td><td><span>$1</span></td><td><span>$2</span></td><td><span>$0.1</span></td><td><span>—</span></td><td><button type="button" aria-label="Capabilities: Text input, Vision"></button></td></tr>` +
        `</tbody></table>`
      const dir = await mkdtemp(join(tmpdir(), "cc-ladders-vision-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: API_UNLISTED,
        registry: REGISTRY,
        factsMd: MODELS_MD([
          `| \`${MODEL}\` | GPT-5.4 | 1M | — | $1/$2 · cache $0.1 | Go | best |`,
        ]),
        modalitiesBundle: `const models = { U: { id: "vendor/unrelated", name: "U", inputModalities: ["text"], contextWindow: 1e6 } }`,
        rscGoat: "",
        rscPro: "",
        modelsPageHtml: modelsPage,
      })
      const env = {
        ...process.env,
        COMMANDCODE_API_BASE: mock.url,
        COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
        COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
        COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
        COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
        COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        COMMANDCODE_MODELS_PAGE_URL: `${mock.url}/models-page.html`,
        COMMANDCODE_MODELS_DETAIL_URL: `${mock.url}/model-detail`,
      }
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          env,
        )
        assertEqual(result.status, 0, result.stderr || result.stdout)
        assert(
          result.stdout.includes(
            `modalities ${MODEL}: text + image (from models page Caps Vision bit)`,
          ),
          `expected a page-Vision promotion note, got: ${result.stdout}`,
        )
        const factsText = await readFile(factsOut, "utf-8")
        assert(
          factsText.includes(`"${MODEL}": ["text","image"]`),
          `page-Vision model must gain a text+image facts entry, got: ${factsText.slice(-300)}`,
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
])
