// tests/refresh-deals-rsc.test.ts — refresh script RSC integration
// (wayfinder tickets #82 and #83 on #78).
//
// Spawns `scripts/refresh-deals.mjs` with the RSC env vars pointed at
// the in-process mock Command Code server (which serves the RSC text
// fixtures), reads the generated `src/deals/catalog.ts`, and asserts
// the content matches what the RSC emit function produces. Also
// exercises the 5xx → RSC-fixtures fallback and the per-model parity
// between the RSC path and the previously-shipped HTML path (the HTML
// path is gone — ticket #83 — but the RSC data is a strict superset,
// so a parity test against the SHIPPED catalog is still meaningful).
import { mkdtemp, readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { spawn } from "node:child_process"
import { readFileSync } from "node:fs"
import { startMockCc } from "./helpers/mock-cc.js"
import { extractPlanPageRsc } from "../scripts/parse-rsc.mjs"
import { emitDealsModuleFromRsc } from "../scripts/refresh-deals.mjs"
import { MODEL_SNAPSHOT } from "../src/catalog/snapshot.js"
import { assert, assertEqual, run } from "./harness.js"

const RSC_PRICING = readFileSync(
  new URL("./fixtures/rsc-pricing-limits.txt", import.meta.url),
  "utf-8",
)
const RSC_GOAT = readFileSync(new URL("./fixtures/rsc-goat.txt", import.meta.url), "utf-8")
const RSC_PRO = readFileSync(new URL("./fixtures/rsc-pro.txt", import.meta.url), "utf-8")

// Async spawn: the in-process mock server must keep serving while the child
// process fetches, so the parent event loop cannot be blocked.
function runScript(args, env): Promise<{ status: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn("node", args, { env, stdio: ["ignore", "pipe", "pipe"] })
    let stdout = ""
    let stderr = ""
    child.stdout.on("data", (chunk) => (stdout += chunk))
    child.stderr.on("data", (chunk) => (stderr += chunk))
    child.on("error", reject)
    child.on("close", (status) => resolve({ status, stdout, stderr }))
  })
}

// Parse the MODEL_DEALS section out of a generated catalog module. The
// module is a TS file with the deals data as a const literal; we
// return the set of model entries (id → body) so per-model assertions
// can compare against expected values. Each entry is on a single line
// of the form `  "id": { ... },`; we capture the body by counting
// brace depth (a naive regex stops at the first `}` which is too
// early for entries containing nested objects like `benchmark: {…}`).
function getModelEntries(text) {
  const out = new Map()
  for (const line of text.split("\n")) {
    const start = line.indexOf('"')
    if (start < 0) continue
    const idEnd = line.indexOf('":', start)
    if (idEnd < 0) continue
    const id = line.slice(start + 1, idEnd)
    const bodyStart = line.indexOf("{", idEnd)
    if (bodyStart < 0) continue
    let depth = 0
    let bodyEnd = -1
    for (let i = bodyStart; i < line.length; i++) {
      const c = line[i]
      if (c === "{") depth++
      else if (c === "}") {
        depth--
        if (depth === 0) {
          bodyEnd = i
          break
        }
      }
    }
    if (bodyEnd < 0) continue
    out.set(id, line.slice(bodyStart + 1, bodyEnd))
  }
  return out
}

run([
  [
    "refresh-deals regenerates the deals catalog from RSC mocks",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-rsc-"))
      const out = join(dir, "catalog.ts")
      const mock = await startMockCc({
        rscPricing: RSC_PRICING,
        rscGoat: RSC_GOAT,
        rscPro: RSC_PRO,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-deals.mjs", "--out", out, "--allow-partial"],
          {
            ...process.env,
            COMMANDCODE_RSC_PRICING_URL: `${mock.url}/docs/resources/pricing-limits`,
            COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
            COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
          },
        )
        assertEqual(result.status, 0, result.stderr || result.stdout)
        assertEqual(mock.hits.rscPricing, 1)
        assertEqual(mock.hits.rscGoat, 1)
        assertEqual(mock.hits.rscPro, 1)
        const contents = await readFile(out, "utf-8")
        assert(
          contents.includes("GENERATED by scripts/refresh-deals.mjs"),
          "missing generated header",
        )
        const expected = emitDealsModuleFromRsc({
          pricingLimitsRsc: RSC_PRICING,
          goatRsc: RSC_GOAT,
          proRsc: RSC_PRO,
          lastRefreshed: new Date().toISOString().split("T")[0],
          packageVersion: "docs",
        })
        assertEqual(contents, expected, "subprocess output must match emitDealsModuleFromRsc")
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
  [
    "refresh-deals: 5xx from any RSC endpoint falls back to RSC fixtures",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-rsc-5xx-"))
      const out = join(dir, "catalog.ts")
      // Serve a genuine 5xx from every RSC endpoint — a transient
      // upstream failure. The script falls back to the committed RSC
      // text fixtures (tests/fixtures/rsc-*.txt), the same source the
      // unit tests use.
      const mock = await startMockCc({ rscStatus: 500 })
      try {
        const result = await runScript(
          ["scripts/refresh-deals.mjs", "--out", out, "--allow-partial"],
          {
            ...process.env,
            COMMANDCODE_RSC_PRICING_URL: `${mock.url}/docs/resources/pricing-limits`,
            COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
            COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
          },
        )
        // 5xx from the mock → empty body → fallback to fixtures →
        // exit 0 with the fixture-based catalog.
        assertEqual(result.status, 0, result.stderr || result.stdout)
        const contents = await readFile(out, "utf-8")
        const expected = emitDealsModuleFromRsc({
          pricingLimitsRsc: RSC_PRICING,
          goatRsc: RSC_GOAT,
          proRsc: RSC_PRO,
          lastRefreshed: new Date().toISOString().split("T")[0],
          packageVersion: "docs",
        })
        assertEqual(contents, expected, "fallback must regenerate the same catalog as the fixtures")
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
  [
    "refresh-deals: 4xx from an RSC endpoint fails loudly (no silent fixture fallback)",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-rsc-404-"))
      const out = join(dir, "catalog.ts")
      // The mock returns 404 for an RSC endpoint when its body option
      // is unset. A 404 is a config error (route moved / wrong
      // COMMANDCODE_RSC_*_URL) — the script must exit non-zero and
      // must NOT write a fixture-based catalog as if it were live.
      const mock = await startMockCc({})
      try {
        const result = await runScript(
          ["scripts/refresh-deals.mjs", "--out", out, "--allow-partial"],
          {
            ...process.env,
            COMMANDCODE_RSC_PRICING_URL: `${mock.url}/docs/resources/pricing-limits`,
            COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
            COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
          },
        )
        assert(
          result.status !== 0,
          `4xx must fail loudly, got status ${result.status}: ${result.stdout} ${result.stderr}`,
        )
        assert(
          result.stderr.includes("HTTP 404") || result.stderr.includes("returned HTTP"),
          `stderr must attribute the 4xx, got: ${result.stderr}`,
        )
        // The write must not happen — a partial/live-stamped fixture
        // catalog would silently ship as fresh data.
        let wrote = true
        try {
          await readFile(out, "utf-8")
        } catch {
          wrote = false
        }
        assert(!wrote, "no catalog must be written on a 4xx")
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
  [
    "refresh-deals --fixtures reads the RSC text fixtures without network",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-rsc-fixtures-"))
      const out = join(dir, "catalog.ts")
      // --fixtures skips the network entirely; no env vars needed.
      const result = await runScript(
        ["scripts/refresh-deals.mjs", "--out", out, "--fixtures", "--allow-partial"],
        { ...process.env },
      )
      assertEqual(result.status, 0, result.stderr || result.stdout)
      const contents = await readFile(out, "utf-8")
      const expected = emitDealsModuleFromRsc({
        pricingLimitsRsc: RSC_PRICING,
        goatRsc: RSC_GOAT,
        proRsc: RSC_PRO,
        lastRefreshed: new Date().toISOString().split("T")[0],
        packageVersion: "docs",
      })
      assertEqual(
        contents,
        expected,
        "--fixtures must produce the same catalog as the live RSC path",
      )
      await rm(dir, { recursive: true, force: true })
    },
  ],
  [
    "refresh-deals: every RSC fixture record maps to a snapshot id (no drift)",
    () => {
      // The RSC's per-plan (goat, pro) slug records are the source of
      // truth for the snapshot id. Every record in the RSC must
      // resolve to a snapshot id; otherwise the refresh script's RSC
      // path drops it (per the missing-snapshot-id guard in #82) and
      // the deals catalog silently loses the model.
      const snapshotIds = new Set(MODEL_SNAPSHOT.map((model) => model.id))
      for (const rscText of [RSC_GOAT, RSC_PRO]) {
        const records = extractPlanPageRsc(rscText)
        for (const [sid, record] of records) {
          assert(
            snapshotIds.has(sid),
            `RSC record id=${sid} name=${record.name} is not in the snapshot`,
          )
        }
      }
    },
  ],
  [
    "refresh-deals: emitted catalog carries the expected structural fields per shape (synthetic-shape pin)",
    () => {
      // The shipped src/deals/catalog.ts is regenerated by
      // `npm run refresh:deals` from the same RSC data. Per-shape
      // parity on a handful of representative models (one per data
      // shape) pins that the RSC path produces the same output the
      // shipping release would.
      //
      // This test is **structural** on purpose: it asserts the
      // fields that the deals consumers rely on (discount, benchmark,
      // allowance, peakOffPeak) are present, but it does NOT pin the
      // exact values — Command Code can change a model's `pct`,
      // `tokPerSec`, or plan allowance without breaking the shape.
      // Pinning those values here (the previous version pinned
      // MiniMax M3's goat=47/pro=57, Kimi K3's goat=20/pro=30)
      // forced a human to update the test before the catalog-refresh
      // cron could ship any value change (issue #89). The modelDealEntry
      // synthetic tests in tests/refresh-deals.test.ts own the value
      // semantics; this test only owns the structural ones.
      const out = emitDealsModuleFromRsc({
        pricingLimitsRsc: RSC_PRICING,
        goatRsc: RSC_GOAT,
        proRsc: RSC_PRO,
        lastRefreshed: "2026-08-28",
        packageVersion: "docs",
      })
      const entries = getModelEntries(out)
      // MiniMax M3: has an active deal + benchmark + allowance. The
      // values aren't pinned.
      const minimax = entries.get("MiniMaxAI/MiniMax-M3") ?? ""
      assert(minimax.includes("discount"), "MiniMax M3 must carry a discount field")
      assert(minimax.includes("benchmark:"), "MiniMax M3 must carry a benchmark field")
      assert(minimax.includes("allowance:"), "MiniMax M3 must carry an allowance field")
      assert(
        minimax.includes('"goat":') && minimax.includes('"pro":'),
        "MiniMax M3 allowance must include both goat and pro keys",
      )
      // moonshotai/Kimi-K3: has an allowance with both goat and pro.
      const kimi = entries.get("moonshotai/Kimi-K3") ?? ""
      assert(kimi.includes("allowance:"), "Kimi K3 must carry an allowance field")
      assert(
        kimi.includes('"goat":') && kimi.includes('"pro":'),
        "Kimi K3 allowance must include both goat and pro keys",
      )
      // DeepSeek V4 Flash: peakOffPeak (the structural field, not
      // the values).
      const ds = entries.get("deepseek/deepseek-v4-flash") ?? ""
      assert(ds.includes("peakOffPeak"), "DeepSeek V4 Flash must carry peakOffPeak")
    },
  ],
])
