// tests/refresh-deals-rsc.test.ts — refresh script RSC integration
// (wayfinder tickets #82 and #83 on #78).
//
// Spawns `scripts/refresh-deals.mjs` with the RSC env vars pointed at
// the in-process mock Command Code server (which serves the RSC text
// fixtures), reads the generated `src/deals/catalog.ts`, and asserts
// the content matches what the RSC emit function produces. Also
// exercises the 5xx → RSC-fixtures fallback and the per-model parity
// between the RSC path and the previously-shipped HTML path (the HTML
// path is gone — ticket #83 — but the RSC data is a strict superset,
// so a parity test against the SHIPPED catalog is still meaningful).
import { mkdtemp, readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { spawn } from "node:child_process"
import { readFileSync } from "node:fs"
import { startMockCc } from "./helpers/mock-cc.js"
import { extractPlanPageRsc } from "../scripts/parse-rsc.mjs"
import { emitDealsModuleFromRsc } from "../scripts/refresh-deals.mjs"
import { MODEL_SNAPSHOT } from "../src/catalog/snapshot.js"
import { assert, assertEqual, run } from "./harness.js"

const RSC_PRICING = readFileSync(
  new URL("./fixtures/rsc-pricing-limits.txt", import.meta.url),
  "utf-8",
)
const RSC_GOAT = readFileSync(new URL("./fixtures/rsc-goat.txt", import.meta.url), "utf-8")
const RSC_PRO = readFileSync(new URL("./fixtures/rsc-pro.txt", import.meta.url), "utf-8")

// Async spawn: the in-process mock server must keep serving while the child
// process fetches, so the parent event loop cannot be blocked.
function runScript(args, env): Promise<{ status: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn("node", args, { env, stdio: ["ignore", "pipe", "pipe"] })
    let stdout = ""
    let stderr = ""
    child.stdout.on("data", (chunk) => (stdout += chunk))
    child.stderr.on("data", (chunk) => (stderr += chunk))
    child.on("error", reject)
    child.on("close", (status) => resolve({ status, stdout, stderr }))
  })
}

// Parse the MODEL_DEALS section out of a generated catalog module. The
// module is a TS file with the deals data as a const literal; we
// return the set of model entries (id → body) so per-model assertions
// can compare against expected values. Each entry is on a single line
// of the form `  "id": { ... },`; we capture the body by counting
// brace depth (a naive regex stops at the first `}` which is too
// early for entries containing nested objects like `benchmark: {…}`).
function getModelEntries(text) {
  const out = new Map()
  for (const line of text.split("\n")) {
    const start = line.indexOf('"')
    if (start < 0) continue
    const idEnd = line.indexOf('":', start)
    if (idEnd < 0) continue
    const id = line.slice(start + 1, idEnd)
    const bodyStart = line.indexOf("{", idEnd)
    if (bodyStart < 0) continue
    let depth = 0
    let bodyEnd = -1
    for (let i = bodyStart; i < line.length; i++) {
      const c = line[i]
      if (c === "{") depth++
      else if (c === "}") {
        depth--
        if (depth === 0) {
          bodyEnd = i
          break
        }
      }
    }
    if (bodyEnd < 0) continue
    out.set(id, line.slice(bodyStart + 1, bodyEnd))
  }
  return out
}

run([
  [
    "refresh-deals regenerates the deals catalog from RSC mocks",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-rsc-"))
      const out = join(dir, "catalog.ts")
      const mock = await startMockCc({
        rscPricing: RSC_PRICING,
        rscGoat: RSC_GOAT,
        rscPro: RSC_PRO,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-deals.mjs", "--out", out, "--allow-partial"],
          {
            ...process.env,
            COMMANDCODE_RSC_PRICING_URL: `${mock.url}/docs/rsc/pricing-limits`,
            COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/rsc/plans/goat`,
            COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/rsc/plans/pro`,
          },
        )
        assertEqual(result.status, 0, result.stderr || result.stdout)
        assertEqual(mock.hits.rscPricing, 1)
        assertEqual(mock.hits.rscGoat, 1)
        assertEqual(mock.hits.rscPro, 1)
        const contents = await readFile(out, "utf-8")
        assert(
          contents.includes("GENERATED by scripts/refresh-deals.mjs"),
          "missing generated header",
        )
        const expected = emitDealsModuleFromRsc({
          pricingLimitsRsc: RSC_PRICING,
          goatRsc: RSC_GOAT,
          proRsc: RSC_PRO,
          lastRefreshed: new Date().toISOString().split("T")[0],
          packageVersion: "docs",
        })
        assertEqual(contents, expected, "subprocess output must match emitDealsModuleFromRsc")
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
  [
    "refresh-deals: 5xx from any RSC endpoint falls back to RSC fixtures",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-rsc-5xx-"))
      const out = join(dir, "catalog.ts")
      // Don't serve the RSC endpoints — the mock returns 404 for them
      // when the option is unset, which the script treats as a fetch
      // failure. The fall-back path then reads the committed RSC text
      // fixtures (tests/fixtures/rsc-*.txt), the same source the unit
      // tests use.
      const mock = await startMockCc({})
      try {
        const result = await runScript(
          ["scripts/refresh-deals.mjs", "--out", out, "--allow-partial"],
          {
            ...process.env,
            COMMANDCODE_RSC_PRICING_URL: `${mock.url}/docs/rsc/pricing-limits`,
            COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/rsc/plans/goat`,
            COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/rsc/plans/pro`,
          },
        )
        // 404 from the mock → empty body → fallback to fixtures →
        // exit 0 with the fixture-based catalog.
        assertEqual(result.status, 0, result.stderr || result.stdout)
        const contents = await readFile(out, "utf-8")
        const expected = emitDealsModuleFromRsc({
          pricingLimitsRsc: RSC_PRICING,
          goatRsc: RSC_GOAT,
          proRsc: RSC_PRO,
          lastRefreshed: new Date().toISOString().split("T")[0],
          packageVersion: "docs",
        })
        assertEqual(contents, expected, "fallback must regenerate the same catalog as the fixtures")
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
  [
    "refresh-deals --fixtures reads the RSC text fixtures without network",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-rsc-fixtures-"))
      const out = join(dir, "catalog.ts")
      // --fixtures skips the network entirely; no env vars needed.
      const result = await runScript(
        ["scripts/refresh-deals.mjs", "--out", out, "--fixtures", "--allow-partial"],
        { ...process.env },
      )
      assertEqual(result.status, 0, result.stderr || result.stdout)
      const contents = await readFile(out, "utf-8")
      const expected = emitDealsModuleFromRsc({
        pricingLimitsRsc: RSC_PRICING,
        goatRsc: RSC_GOAT,
        proRsc: RSC_PRO,
        lastRefreshed: new Date().toISOString().split("T")[0],
        packageVersion: "docs",
      })
      assertEqual(
        contents,
        expected,
        "--fixtures must produce the same catalog as the live RSC path",
      )
      await rm(dir, { recursive: true, force: true })
    },
  ],
  [
    "refresh-deals: every RSC fixture record maps to a snapshot id (no drift)",
    () => {
      // The RSC's per-plan (goat, pro) slug records are the source of
      // truth for the snapshot id. Every record in the RSC must
      // resolve to a snapshot id; otherwise the refresh script's RSC
      // path drops it (per the missing-snapshot-id guard in #82) and
      // the deals catalog silently loses the model.
      const snapshotIds = new Set(MODEL_SNAPSHOT.map((model) => model.id))
      for (const rscText of [RSC_GOAT, RSC_PRO]) {
        const records = extractPlanPageRsc(rscText)
        for (const [sid, record] of records) {
          assert(
            snapshotIds.has(sid),
            `RSC record id=${sid} name=${record.name} is not in the snapshot`,
          )
        }
      }
    },
  ],
  [
    "refresh-deals: emitted catalog has parity with the shipped catalog on key models",
    () => {
      // The shipped src/deals/catalog.ts is regenerated by
      // `npm run refresh:deals` from the same RSC data. Per-model
      // parity on a handful of representative models (one per data
      // shape) pins that the RSC path produces the same output the
      // shipping release would. The "tier" field may differ on the
      // 7 known tier flips #86 will fix; the structural fields
      // (discount, was, now, allowance) must match.
      const out = emitDealsModuleFromRsc({
        pricingLimitsRsc: RSC_PRICING,
        goatRsc: RSC_GOAT,
        proRsc: RSC_PRO,
        lastRefreshed: "2026-08-28",
        packageVersion: "docs",
      })
      const entries = getModelEntries(out)
      // MiniMax M3: discount + was + now + benchmark + allowance.
      const minimax = entries.get("MiniMaxAI/MiniMax-M3") ?? ""
      assert(minimax.includes("discount"), "MiniMax M3 must carry discount")
      assert(minimax.includes("benchmark:"), "MiniMax M3 must carry benchmark")
      assert(
        minimax.includes("allowance:") &&
          minimax.includes('"goat":47') &&
          minimax.includes('"pro":57'),
        "MiniMax M3 must carry RSC-derived GOAT/PRO allowances",
      )
      // moonshotai/Kimi-K3: goat=20, pro=30.
      const kimi = entries.get("moonshotai/Kimi-K3") ?? ""
      assert(
        kimi.includes('"goat":20') && kimi.includes('"pro":30'),
        "Kimi K3 must carry RSC allowances",
      )
      // DeepSeek V4 Flash: peakOffPeak.
      const ds = entries.get("deepseek/deepseek-v4-flash") ?? ""
      assert(ds.includes("peakOffPeak"), "DeepSeek V4 Flash must carry peakOffPeak")
    },
  ],
])
