// tests/refresh-classification.test.ts — seam: the reasoning-classification
// generator CLI (scripts/refresh-classification.mjs, issue #110). Mirrors
// the Snapshot generator's tests: the script is spawned as a subprocess
// with env-overridden RSC URLs pointed at the in-process mock server,
// which serves **synthetic** slug records — never upstream's current
// values. Locks: capability emitted per model; the Snapshot-coverage gate
// failing loudly and naming the missing models; the loud shape failure
// when the reasoning flag is absent; the ADR-0005 fetch semantics via the
// shared record source; the override seam applying at generation time.
import { mkdtemp, readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { spawn } from "node:child_process"
import { readFileSync } from "node:fs"
import { startMockCc } from "./helpers/mock-cc.js"
import { snapshotIndex } from "../scripts/snapshot-index.mjs"
import {
  buildClassificationModule,
  emitClassificationModuleFromRsc,
} from "../scripts/refresh-classification.mjs"
import { assert, assertEqual, run } from "./harness.js"

const RSC_GOAT = readFileSync(new URL("./fixtures/rsc-goat.txt", import.meta.url), "utf-8")
const RSC_PRO = readFileSync(new URL("./fixtures/rsc-pro.txt", import.meta.url), "utf-8")

const TODAY = new Date().toISOString().split("T")[0]

// Async spawn: the in-process mock server must keep serving while the child
// process fetches, so the parent event loop cannot be blocked.
function runScript(args, env): Promise<{ status: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn("node", args, { env, stdio: ["ignore", "pipe", "pipe"] })
    let stdout = ""
    let stderr = ""
    child.stdout.on("data", (chunk) => (stdout += chunk))
    child.stderr.on("data", (chunk) => (stderr += chunk))
    child.on("error", reject)
    child.on("close", (status) => resolve({ status, stdout, stderr }))
  })
}

// Builds a synthetic per-plan slug record with the full required field
// shape (the same fields the parser pins, plus the reasoning flag).
function slugRecord(id, name, reasoning) {
  return {
    slug: id.split("/").pop(),
    id,
    name,
    vendor: id.includes("/") ? id.split("/")[0] : id,
    category: "opensource",
    minPlanName: "Go",
    tiers: [],
    caps: {},
    reasoning,
  }
}

// Builds a synthetic RSC flight payload embedding the slug-records array.
// The parser identifies the array by its first element's shape, and the
// predicate requires the first id to be vendor-prefixed (`/` in it) —
// put a vendor-prefixed record first, exactly like the live payload.
function slugPayload(records) {
  return `2:${JSON.stringify(records)}\n`
}

// A synthetic payload covering **every** snapshot model, so the coverage
// gate passes and the emitted map is fully determined by this test's own
// data (never by upstream's current values).
function fullCoveragePayload(reasoningById) {
  const { byId } = snapshotIndex()
  const records = [...byId.entries()].map(([id, name]) =>
    slugRecord(id, name, reasoningById.has(id) ? reasoningById.get(id) : true),
  )
  // First record must carry a vendor-prefixed id for the parser's array
  // predicate; rotate the array so one does.
  const firstVendor = records.findIndex((r) => r.id.includes("/"))
  if (firstVendor > 0) {
    records.unshift(...records.splice(firstVendor, 1))
  }
  return slugPayload(records)
}

run([
  [
    "refresh-classification emits the capability per model from synthetic records (CLI seam)",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-classification-"))
      const out = join(dir, "classification.ts")
      const reasoning = new Map([
        ["claude-sonnet-5", true],
        ["moonshotai/Kimi-K2.6", false],
        ["tencent/hy3-paid", true],
      ])
      const payload = fullCoveragePayload(reasoning)
      const mock = await startMockCc({ rscGoat: payload, rscPro: payload })
      try {
        const result = await runScript(["scripts/refresh-classification.mjs", "--out", out], {
          ...process.env,
          COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
          COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        })
        assertEqual(result.status, 0, result.stderr || result.stdout)
        // Page subset: the per-plan pages only — the pricing-limits page
        // must not be fetched (no extra network).
        assertEqual(mock.hits.rscPricing, 0, "pricing-limits page must not be fetched")
        assertEqual(mock.hits.rscGoat, 1)
        assertEqual(mock.hits.rscPro, 1)
        const contents = await readFile(out, "utf-8")
        assert(
          contents.includes("GENERATED by scripts/refresh-classification.mjs"),
          "missing generated header",
        )
        assert(contents.includes("Do not edit"), "missing do-not-edit marker")
        const mod = await import(out)
        assertEqual(mod.MODEL_REASONING_CAPABILITY["claude-sonnet-5"], true)
        assertEqual(mod.MODEL_REASONING_CAPABILITY["moonshotai/Kimi-K2.6"], false)
        assertEqual(mod.MODEL_REASONING_CAPABILITY["tencent/hy3-paid"], true)
        assertEqual(mod.CLASSIFICATION_LAST_REFRESHED, TODAY)
        // Every snapshot model got an entry — the coverage gate held.
        const { byId } = snapshotIndex()
        for (const id of byId.keys()) {
          assertEqual(typeof mod.MODEL_REASONING_CAPABILITY[id], "boolean", id)
        }
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
  [
    "refresh-classification fails loudly when a snapshot model has no RSC record (coverage gate)",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-classification-coverage-"))
      const out = join(dir, "classification.ts")
      // One synthetic model only — every other snapshot model is missing.
      const payload = slugPayload([slugRecord("moonshotai/Kimi-K3", "Kimi K3", true)])
      const mock = await startMockCc({ rscGoat: payload, rscPro: payload })
      try {
        const result = await runScript(["scripts/refresh-classification.mjs", "--out", out], {
          ...process.env,
          COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
          COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        })
        assert(result.status !== 0, `expected non-zero exit, got ${result.status}`)
        assert(
          result.stderr.includes("claude-sonnet-5"),
          `coverage failure must name a missing model, got: ${result.stderr}`,
        )
        assert(
          /no RSC record/.test(result.stderr),
          `coverage failure must state the reason, got: ${result.stderr}`,
        )
        let wrote = true
        try {
          await readFile(out, "utf-8")
        } catch {
          wrote = false
        }
        assert(!wrote, "no module must be written when the coverage gate fails")
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
  [
    "refresh-classification fails loudly when the reasoning flag is absent (shape gate)",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-classification-shape-"))
      const out = join(dir, "classification.ts")
      // Full coverage, but the reasoning flag is deleted from one record —
      // the loud shape failure must name that model and the flag, never
      // default it to non-reasoning.
      const payload = fullCoveragePayload(new Map())
      const records = JSON.parse(payload.slice(2))
      const victim = records.find((r) => r.id === "moonshotai/Kimi-K3")
      delete victim.reasoning
      const broken = slugPayload(records)
      const mock = await startMockCc({ rscGoat: broken, rscPro: broken })
      try {
        const result = await runScript(["scripts/refresh-classification.mjs", "--out", out], {
          ...process.env,
          COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
          COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        })
        assert(result.status !== 0, `expected non-zero exit, got ${result.status}`)
        assert(
          result.stderr.includes("moonshotai/Kimi-K3") && result.stderr.includes("reasoning"),
          `shape failure must name the model and the missing field, got: ${result.stderr}`,
        )
        let wrote = true
        try {
          await readFile(out, "utf-8")
        } catch {
          wrote = false
        }
        assert(!wrote, "no module must be written on a shape failure")
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
  [
    "refresh-classification: 5xx from the per-plan pages falls back to the committed fixtures",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-classification-5xx-"))
      const out = join(dir, "classification.ts")
      const mock = await startMockCc({ rscStatus: 500 })
      try {
        const result = await runScript(["scripts/refresh-classification.mjs", "--out", out], {
          ...process.env,
          COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
          COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        })
        assertEqual(result.status, 0, result.stderr || result.stdout)
        const contents = await readFile(out, "utf-8")
        const expected = emitClassificationModuleFromRsc({
          goatRsc: RSC_GOAT,
          proRsc: RSC_PRO,
          lastRefreshed: TODAY,
        }).module
        assertEqual(
          contents,
          expected,
          "fallback must regenerate the same classification as the fixtures",
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
  [
    "refresh-classification: 4xx from a per-plan page fails loudly (no silent fixture fallback)",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-classification-4xx-"))
      const out = join(dir, "classification.ts")
      const mock = await startMockCc({})
      try {
        const result = await runScript(["scripts/refresh-classification.mjs", "--out", out], {
          ...process.env,
          COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
          COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        })
        assert(
          result.status !== 0,
          `4xx must fail loudly, got status ${result.status}: ${result.stdout} ${result.stderr}`,
        )
        assert(
          result.stderr.includes("HTTP 404") || result.stderr.includes("returned HTTP"),
          `stderr must attribute the 4xx, got: ${result.stderr}`,
        )
        let wrote = true
        try {
          await readFile(out, "utf-8")
        } catch {
          wrote = false
        }
        assert(!wrote, "no module must be written on a 4xx")
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
  [
    "refresh-classification --fixtures reads the committed fixtures without network",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-classification-fixtures-"))
      const out = join(dir, "classification.ts")
      const result = await runScript(
        ["scripts/refresh-classification.mjs", "--out", out, "--fixtures"],
        {
          ...process.env,
        },
      )
      assertEqual(result.status, 0, result.stderr || result.stdout)
      const contents = await readFile(out, "utf-8")
      const expected = emitClassificationModuleFromRsc({
        goatRsc: RSC_GOAT,
        proRsc: RSC_PRO,
        lastRefreshed: TODAY,
      }).module
      assertEqual(contents, expected, "--fixtures must match the fixture-based emit")
      await rm(dir, { recursive: true, force: true })
    },
  ],
  [
    "buildClassificationModule is deterministic (same inputs → same bytes)",
    () => {
      const records = new Map([
        ["moonshotai/Kimi-K3", slugRecord("moonshotai/Kimi-K3", "Kimi K3", true)],
        ["moonshotai/Kimi-K2.6", slugRecord("moonshotai/Kimi-K2.6", "Kimi K2.6", false)],
        ["claude-sonnet-5", slugRecord("claude-sonnet-5", "Claude Sonnet 5", true)],
      ])
      const a = buildClassificationModule({ bySnapshotId: records, lastRefreshed: "2026-09-03" })
      const b = buildClassificationModule({ bySnapshotId: records, lastRefreshed: "2026-09-03" })
      assertEqual(a, b)
      // Sorted output, per-model lines.
      const kimiLine = a.indexOf('"moonshotai/Kimi-K2.6": false')
      const sonnetLine = a.indexOf('"claude-sonnet-5": true')
      assert(kimiLine >= 0 && sonnetLine >= 0, `missing capability lines in: ${a}`)
    },
  ],
  [
    "buildClassificationModule applies an override at generation time",
    () => {
      const records = new Map([
        ["moonshotai/Kimi-K3", slugRecord("moonshotai/Kimi-K3", "Kimi K3", true)],
      ])
      const out = buildClassificationModule({
        bySnapshotId: records,
        lastRefreshed: "2026-09-03",
        overrides: {
          "moonshotai/Kimi-K3": {
            capability: false,
            justification: "upstream RSC flag says true but models.md omits reasoning",
          },
        },
      })
      assert(
        out.includes('"moonshotai/Kimi-K3": false'),
        `override capability must win, got: ${out.slice(0, 400)}`,
      )
      // The applied override (with its justification) is embedded in the
      // module so the refresh PR body can render it.
      assert(
        out.includes("upstream RSC flag says true but models.md omits reasoning"),
        "the module must embed the active overrides with their justifications",
      )
    },
  ],
  [
    "buildClassificationModule rejects a note-less override at generation time",
    () => {
      const records = new Map([
        ["moonshotai/Kimi-K3", slugRecord("moonshotai/Kimi-K3", "Kimi K3", true)],
      ])
      let message = ""
      try {
        buildClassificationModule({
          bySnapshotId: records,
          lastRefreshed: "2026-09-03",
          overrides: { "moonshotai/Kimi-K3": { capability: false } },
        })
      } catch (error) {
        message = error instanceof Error ? error.message : String(error)
      }
      assert(
        message.includes("moonshotai/Kimi-K3") && /justification/.test(message),
        `expected a loud justification failure, got: ${message}`,
      )
    },
  ],
])
