// tests/refresh-snapshot.test.ts — refresh script integration (issue #16, seam 3)
import { mkdtemp, readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { spawn } from "node:child_process"
import { startMockCc } from "./helpers/mock-cc.js"
import { assert, assertEqual, run } from "./harness.js"

const MODELS_PAYLOAD = {
  object: "list",
  data: [
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", context_length: 200000 },
    {
      id: "deepseek/deepseek-v4-flash",
      name: "DeepSeek V4 Flash (latest)",
      context_length: 1000000,
    },
  ],
}

const FACTS_MD =
  "## Open Source\n\n" +
  "| Id | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
  "|---|---|---|---|---|---|---|\n" +
  "| `claude-sonnet-5` | Claude Sonnet 5 | 1M | low, medium, high, xhigh, max | $2/$10 · cache $0.2 (write $2.5) | Pro and above | best |\n"

// Async spawn: the in-process mock server must keep serving while the child
// process fetches the catalog, so the parent event loop cannot be blocked.
function runScript(args, env): Promise<{ status: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn("node", args, { env, stdio: ["ignore", "pipe", "pipe"] })
    let stdout = ""
    let stderr = ""
    child.stdout.on("data", (chunk) => (stdout += chunk))
    child.stderr.on("data", (chunk) => (stderr += chunk))
    child.on("error", reject)
    child.on("close", (status) => resolve({ status, stdout, stderr }))
  })
}

run([
  [
    "refresh-snapshot regenerates the snapshot from the catalog endpoint",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: MODELS_PAYLOAD,
        registry: { "dist-tags": { latest: "1.28.1" } },
        factsMd: FACTS_MD,
      })
      try {
        const result = await runScript(["scripts/refresh-snapshot.mjs", "--out", out], {
          ...process.env,
          COMMANDCODE_API_BASE: mock.url,
          COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
          COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
        })
        assert(result.status === 0, result.stderr || result.stdout)
        assertEqual(mock.hits.models, 1)
        const contents = await readFile(out, "utf-8")
        assert(
          contents.includes("GENERATED by scripts/refresh-snapshot.mjs"),
          "missing generated header",
        )
        const mod = await import(out)
        assertEqual(mod.MODEL_SNAPSHOT, [
          { id: "claude-sonnet-5", name: "Claude Sonnet 5", contextLength: 200000 },
          {
            id: "deepseek/deepseek-v4-flash",
            name: "DeepSeek V4 Flash (latest)",
            contextLength: 1000000,
          },
        ])
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "refresh-snapshot writes generated facts.ts next to the snapshot",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-facts-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: MODELS_PAYLOAD,
        registry: { "dist-tags": { latest: "1.28.1" } },
        factsMd: FACTS_MD,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          {
            ...process.env,
            COMMANDCODE_API_BASE: mock.url,
            COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
            COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
          },
        )
        assert(result.status === 0, result.stderr || result.stdout)
        const contents = await readFile(factsOut, "utf-8")
        assert(
          contents.includes("GENERATED by scripts/refresh-snapshot.mjs"),
          "missing generated header",
        )
        assert(contents.includes('FACTS_PACKAGE_VERSION = "1.28.1"'), "missing package version")
        const mod = await import(factsOut)
        assertEqual(mod.MODEL_EFFORTS, {
          "claude-sonnet-5": ["low", "medium", "high", "xhigh", "max"],
        })
        assertEqual(mod.MODEL_COSTS, {
          "claude-sonnet-5": { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 },
        })
        assertEqual(mod.FACTS_LAST_REFRESHED, new Date().toISOString().split("T")[0])
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "refresh-snapshot fails loudly when the registry body is not JSON",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-registry-parse-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: MODELS_PAYLOAD,
        registryRaw: "<html>not json</html>",
        factsMd: FACTS_MD,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          {
            ...process.env,
            COMMANDCODE_API_BASE: mock.url,
            COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
            COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
          },
        )
        assert(result.status !== 0, `expected non-zero exit, got ${result.status}`)
        assert(
          result.stderr.includes("could not parse"),
          `expected 'could not parse' in stderr, got: ${result.stderr}`,
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
])
