// tests/refresh-snapshot.test.ts — refresh script integration (issue #16, seam 3)
import { mkdtemp, readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { spawn } from "node:child_process"
import { startMockCc } from "./helpers/mock-cc.js"
import { assert, assertEqual, run } from "./harness.js"

const MODELS_PAYLOAD = {
  object: "list",
  data: [
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", context_length: 200000 },
    {
      id: "deepseek/deepseek-v4-flash",
      name: "DeepSeek V4 Flash (latest)",
      context_length: 1000000,
    },
  ],
}

const FACTS_MD =
  "## Open Source\n\n" +
  "| Id | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
  "|---|---|---|---|---|---|---|\n" +
  "| `claude-sonnet-5` | Claude Sonnet 5 | 1M | low, medium, high, xhigh, max | $2/$10 · cache $0.2 (write $2.5) | Pro and above | best |\n"

const MODALITIES_BUNDLE =
  'const models={SONNET:{name:"Claude Sonnet 5",id:"claude-sonnet-5",inputModalities:["text","image"],contextWindow:2e5},' +
  'FLASH:{inputModalities:["text"],id:"deepseek/deepseek-v4-flash",label:"DeepSeek",contextWindow:1e6}}'

// Async spawn: the in-process mock server must keep serving while the child
// process fetches the catalog, so the parent event loop cannot be blocked.
function runScript(args, env): Promise<{ status: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn("node", args, { env, stdio: ["ignore", "pipe", "pipe"] })
    let stdout = ""
    let stderr = ""
    child.stdout.on("data", (chunk) => (stdout += chunk))
    child.stderr.on("data", (chunk) => (stderr += chunk))
    child.on("error", reject)
    child.on("close", (status) => resolve({ status, stdout, stderr }))
  })
}

run([
  [
    "refresh-snapshot regenerates the snapshot from the catalog endpoint",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: MODELS_PAYLOAD,
        registry: { "dist-tags": { latest: "1.28.1" } },
        factsMd: FACTS_MD,
        modalitiesBundle: MODALITIES_BUNDLE,
      })
      try {
        const result = await runScript(["scripts/refresh-snapshot.mjs", "--out", out], {
          ...process.env,
          COMMANDCODE_API_BASE: mock.url,
          COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
          COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
          COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
        })
        assert(result.status === 0, result.stderr || result.stdout)
        assertEqual(mock.hits.models, 1)
        const contents = await readFile(out, "utf-8")
        assert(
          contents.includes("GENERATED by scripts/refresh-snapshot.mjs"),
          "missing generated header",
        )
        const mod = await import(out)
        assertEqual(mod.MODEL_SNAPSHOT, [
          { id: "claude-sonnet-5", name: "Claude Sonnet 5", contextLength: 200000 },
          {
            id: "deepseek/deepseek-v4-flash",
            name: "DeepSeek V4 Flash (latest)",
            contextLength: 1000000,
          },
        ])
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "refresh-snapshot writes generated facts.ts next to the snapshot",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-facts-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: MODELS_PAYLOAD,
        registry: { "dist-tags": { latest: "1.28.1" } },
        factsMd: FACTS_MD,
        modalitiesBundle: MODALITIES_BUNDLE,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          {
            ...process.env,
            COMMANDCODE_API_BASE: mock.url,
            COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
            COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
            COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
          },
        )
        assert(result.status === 0, result.stderr || result.stdout)
        const contents = await readFile(factsOut, "utf-8")
        assert(
          contents.includes("GENERATED by scripts/refresh-snapshot.mjs"),
          "missing generated header",
        )
        assert(contents.includes('FACTS_PACKAGE_VERSION = "1.28.1"'), "missing package version")
        const mod = await import(factsOut)
        assertEqual(mod.MODEL_EFFORTS, {
          "claude-sonnet-5": ["low", "medium", "high", "xhigh", "max"],
        })
        assertEqual(mod.MODEL_COSTS, {
          "claude-sonnet-5": { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 },
        })
        assertEqual(mod.MODALITIES_SOURCE_URL, `${mock.url}/cli.mjs`)
        assertEqual(mod.MODEL_INPUT_MODALITIES, {
          "claude-sonnet-5": ["text", "image"],
        })
        assertEqual(mod.FACTS_LAST_REFRESHED, new Date().toISOString().split("T")[0])
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "refresh-snapshot drops facts rows for models outside the API snapshot",
    async () => {
      // Upstream skew (run 33922321678): the npm models.md carried a
      // gpt-6-astra row the catalog endpoint no longer served, and the
      // unfiltered facts broke the catalog-metadata suite (facts ⊆
      // snapshot). Facts for non-snapshot ids must be dropped, loudly.
      const dir = await mkdtemp(join(tmpdir(), "cc-facts-ahead-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const aheadMd =
        "## Open Source\n\n" +
        "| Id | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
        "|---|---|---|---|---|---|---|\n" +
        "| `claude-sonnet-5` | Claude Sonnet 5 | 1M | low, medium, high, xhigh, max | $2/$10 · cache $0.2 (write $2.5) | Pro and above | best |\n" +
        "| `gpt-6-astra` | GPT 6 Astra | 1M | low, medium, high | $1/$2 · cache $0.1 | Pro and above | best |\n"
      const mock = await startMockCc({
        models: {
          object: "list",
          data: [{ id: "claude-sonnet-5", name: "Claude Sonnet 5", context_length: 200000 }],
        },
        registry: { "dist-tags": { latest: "1.28.1" } },
        factsMd: aheadMd,
        modalitiesBundle:
          'const models={SONNET:{name:"Claude Sonnet 5",id:"claude-sonnet-5",inputModalities:["text","image"],contextWindow:2e5},' +
          'ASTRA:{name:"GPT 6 Astra",id:"gpt-6-astra",inputModalities:["text"],contextWindow:1e6}}',
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          {
            ...process.env,
            COMMANDCODE_API_BASE: mock.url,
            COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
            COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
            COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
          },
        )
        assert(result.status === 0, result.stderr || result.stdout)
        assert(
          result.stdout.includes("gpt-6-astra"),
          `expected the dropped model to be named in stdout, got: ${result.stdout}`,
        )
        const mod = await import(factsOut)
        // Object-equality style (as in the facts test above): the ahead
        // row must be absent from every map while the snapshot row is kept
        // with its parsed values.
        assertEqual(mod.MODEL_COSTS, {
          "claude-sonnet-5": { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 },
        })
        assertEqual(mod.MODEL_EFFORTS, {
          "claude-sonnet-5": ["low", "medium", "high", "xhigh", "max"],
        })
        assertEqual(mod.MODEL_INPUT_MODALITIES, {
          "claude-sonnet-5": ["text", "image"],
        })
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "refresh-snapshot fails loudly when the registry body is not JSON",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-registry-parse-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: MODELS_PAYLOAD,
        registryRaw: "<html>not json</html>",
        factsMd: FACTS_MD,
        modalitiesBundle: MODALITIES_BUNDLE,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          {
            ...process.env,
            COMMANDCODE_API_BASE: mock.url,
            COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
            COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
            COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
          },
        )
        assert(result.status !== 0, `expected non-zero exit, got ${result.status}`)
        assert(
          result.stderr.includes("could not parse"),
          `expected 'could not parse' in stderr, got: ${result.stderr}`,
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "refresh-snapshot fails when the CLI bundle omits an API model",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-modalities-coverage-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: {
          ...MODELS_PAYLOAD,
          data: [
            ...MODELS_PAYLOAD.data,
            { id: "missing/model", name: "Missing", context_length: 1000 },
          ],
        },
        registry: { "dist-tags": { latest: "1.28.1" } },
        factsMd: FACTS_MD,
        modalitiesBundle: MODALITIES_BUNDLE,
      })
      try {
        const result = await runScript(["scripts/refresh-snapshot.mjs", "--out", out], {
          ...process.env,
          COMMANDCODE_API_BASE: mock.url,
          COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
          COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
          COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
        })
        assert(result.status !== 0, `expected non-zero exit, got ${result.status}`)
        assert(
          result.stderr.includes("missing/model"),
          `expected missing model in stderr, got: ${result.stderr}`,
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
])
