// tests/refresh-snapshot.test.ts — refresh script integration (issue #16 seam 3,
// issue #130: models.md-primary Snapshot membership + ship-bar)
import { mkdtemp, readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { spawn } from "node:child_process"
import { startMockCc } from "./helpers/mock-cc.js"
import { assert, assertEqual, run } from "./harness.js"

// The mock models payload no longer decides Snapshot membership (issue
// #130): the API listing is annotate-only. It exists so tests can drive
// the divergence note.
const API_MODELS = {
  object: "list",
  data: [
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", context_length: 200000 },
    {
      id: "deepseek/deepseek-v4-flash",
      name: "DeepSeek V4 Flash (latest)",
      context_length: 1000000,
    },
    // Deliberately diverges from the package table in one direction (in
    // API but not membership) and is missing another (membership ahead).
  ],
}

const PACKAGE_MD =
  "## Open Source\n\n" +
  "| Id (use EXACTLY this) | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
  "|---|---|---|---|---|---|---|\n" +
  "| `claude-sonnet-5` | Claude Sonnet 5 | 1M | low, medium, high, xhigh, max | $2/$10 · cache $0.2 (write $2.5) | Pro and above | best |\n" +
  "| `gpt-6-astra` | GPT-6 Astra | 1.05M | low, medium, high, xhigh, max | $10/$50 · cache $1 (write $12.5) | Max | best |\n"

const PACKAGE_MD_FREE =
  "## Open Source\n\n" +
  "| Id (use EXACTLY this) | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
  "|---|---|---|---|---|---|---|\n" +
  "| `poolside/laguna-s-2.1-free` | Laguna S 2.1 | 256K | — | $0/$0 · cache $0 | Go and above | best |\n"

const CLI_BUNDLE =
  'const models={SONNET:{name:"Claude Sonnet 5",id:"claude-sonnet-5",inputModalities:["text","image"],contextWindow:2e5},' +
  'FLASH:{name:"DeepSeek V4 Flash (latest)",id:"deepseek/deepseek-v4-flash",inputModalities:["text"],contextWindow:1e6},' +
  'ASTRA:{name:"GPT-6 Astra",id:"gpt-6-astra",inputModalities:["text","image"],contextWindow:105e4}}'

// Async spawn: the in-process mock server must keep serving while the child
// process fetches the catalog, so the parent event loop cannot be blocked.
function runScript(args, env): Promise<{ status: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn("node", args, { env, stdio: ["ignore", "pipe", "pipe"] })
    let stdout = ""
    let stderr = ""
    child.stdout.on("data", (chunk) => (stdout += chunk))
    child.stderr.on("data", (chunk) => (stderr += chunk))
    child.on("error", reject)
    child.on("close", (status) => resolve({ status, stdout, stderr }))
  })
}

function scriptEnv(mock: { url: string }) {
  // Every enrichment source is pointed at the mock (which 404s unless the
  // test provides a body) so a ladder needing a source degrades hermetically
  // — a refresh test must never touch the live Command Code site.
  return {
    ...process.env,
    COMMANDCODE_API_BASE: mock.url,
    COMMANDCODE_REGISTRY_URL: `${mock.url}/registry`,
    COMMANDCODE_FACTS_URL: `${mock.url}/models.md`,
    COMMANDCODE_MODALITIES_URL: `${mock.url}/cli.mjs`,
    COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
    COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
    COMMANDCODE_MODELS_PAGE_URL: `${mock.url}/models-page.html`,
    COMMANDCODE_MODELS_DETAIL_URL: `${mock.url}/model-detail`,
  }
}

run([
  [
    "membership comes from the package models.md, not the listing API; API divergence is note-only",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-refresh-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: API_MODELS,
        registry: { "dist-tags": { latest: "1.49.1" } },
        factsMd: PACKAGE_MD,
        modalitiesBundle: CLI_BUNDLE,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", join(dir, "facts.ts")],
          scriptEnv(mock),
        )
        assert(result.status === 0, result.stderr || result.stdout)
        assertEqual(mock.hits.models, 1)
        // gpt-6-astra is a package row the API does not serve: it must
        // ship (day-1 membership) and the divergence must be a note.
        assert(
          result.stdout.includes("gpt-6-astra"),
          `expected divergence note naming gpt-6-astra, got stdout: ${result.stdout}`,
        )
        const contents = await readFile(out, "utf-8")
        assert(
          contents.includes("GENERATED by scripts/refresh-snapshot.mjs"),
          "missing generated header",
        )
        const mod = await import(out)
        assertEqual(mod.MODEL_SNAPSHOT, [
          {
            id: "claude-sonnet-5",
            name: "Claude Sonnet 5",
            contextLength: 1000000,
            contextSource: "models.md",
            efforts: ["low", "medium", "high", "xhigh", "max"],
            cost: { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 },
            costSource: "models.md",
          },
          {
            id: "gpt-6-astra",
            name: "GPT-6 Astra",
            contextLength: 1050000,
            contextSource: "models.md",
            efforts: ["low", "medium", "high", "xhigh", "max"],
            cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
            costSource: "models.md",
          },
        ])
        // The facts shim derives the maps from the package rows.
        const factsMod = await import(join(dir, "facts.ts"))
        assertEqual(factsMod.MODEL_COSTS, {
          "claude-sonnet-5": { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 },
          "gpt-6-astra": { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
        })
        assertEqual(factsMod.MODEL_EFFORTS, {
          "claude-sonnet-5": ["low", "medium", "high", "xhigh", "max"],
          "gpt-6-astra": ["low", "medium", "high", "xhigh", "max"],
        })
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "a package-ahead row (day-1 model) is the ship case: ships with decimal-parsed context, costs, efforts",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-facts-ahead-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: {
          object: "list",
          data: [{ id: "claude-sonnet-5", name: "Claude Sonnet 5", context_length: 200000 }],
        },
        registry: { "dist-tags": { latest: "1.49.1" } },
        factsMd: PACKAGE_MD,
        modalitiesBundle: CLI_BUNDLE,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          scriptEnv(mock),
        )
        assert(result.status === 0, result.stderr || result.stdout)
        assert(
          result.stdout.includes("gpt-6-astra"),
          `expected the divergence note to name the day-1 model, got: ${result.stdout}`,
        )
        const mod = await import(out)
        const astra = mod.MODEL_SNAPSHOT.find((m) => m.id === "gpt-6-astra")
        assert(astra, "gpt-6-astra must ship even when the listing API omits it")
        assertEqual(astra.contextLength, 1050000)
        assertEqual(astra.cost, { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 })
        assertEqual(astra.efforts, ["low", "medium", "high", "xhigh", "max"])
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "the listing API never adds membership: an API-only model is absent from the snapshot",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-api-ahead-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: {
          object: "list",
          data: [
            { id: "claude-sonnet-5", name: "Claude Sonnet 5", context_length: 200000 },
            { id: "api-only/model", name: "API Only", context_length: 12345 },
          ],
        },
        registry: { "dist-tags": { latest: "1.49.1" } },
        factsMd: PACKAGE_MD,
        modalitiesBundle: CLI_BUNDLE,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", join(dir, "facts.ts")],
          scriptEnv(mock),
        )
        assert(result.status === 0, result.stderr || result.stdout)
        assert(
          result.stdout.includes("api-only/model"),
          `expected divergence note naming the API-only model, got stdout: ${result.stdout}`,
        )
        const mod = await import(out)
        assertEqual(
          mod.MODEL_SNAPSHOT.some((m) => m.id === "api-only/model"),
          false,
          "an API-only model must never enter Snapshot membership",
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "an explicitly free package row keeps all-zero costs (free ≠ missing) and reaches the facts map",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-free-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const mock = await startMockCc({
        models: API_MODELS,
        registry: { "dist-tags": { latest: "1.49.1" } },
        factsMd: PACKAGE_MD_FREE,
        modalitiesBundle:
          'const models={FREE:{name:"Laguna S 2.1",id:"poolside/laguna-s-2.1-free",inputModalities:["text"],contextWindow:256e3}}',
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          scriptEnv(mock),
        )
        assert(result.status === 0, result.stderr || result.stdout)
        const mod = await import(out)
        const free = mod.MODEL_SNAPSHOT.find((m) => m.id === "poolside/laguna-s-2.1-free")
        assert(free, "free row must ship")
        assertEqual(free.contextLength, 256000)
        assertEqual(free.cost, { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 })
        const factsMod = await import(factsOut)
        // The facts map must carry the row's cost — derived from the row
        // id (no literal pin; the lint gate forbids literal catalog-index
        // access to a real generated id).
        assertEqual(factsMod.MODEL_COSTS[free.id], free.cost)
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "a missing Context cell resolves through the ordered ladder: models.md (—) → CLI contextWindow, with per-step annotation",
    async () => {
      // Issue #132: a row whose models.md Context cell is "—" is no longer
      // pending — the ordered ladder resolves it. Here the RSC pages are
      // unavailable (mock 404s degrade to notes), so the CLI bundle's
      // contextWindow (200000) resolves the row and the log names the step.
      const dir = await mkdtemp(join(tmpdir(), "cc-ctx-ladder-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: API_MODELS,
        registry: { "dist-tags": { latest: "1.49.1" } },
        factsMd:
          "## Open Source\n\n" +
          "| Id (use EXACTLY this) | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
          "|---|---|---|---|---|---|---|\n" +
          "| `zai-org/GLM-5.1` | GLM-5.1 | — | — | $1.4/$4.4 · cache $0.26 | Go and above | best |\n",
        modalitiesBundle:
          'const models={GLM51:{name:"GLM-5.1",id:"zai-org/GLM-5.1",inputModalities:["text"],contextWindow:2e5}}',
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", join(dir, "facts.ts")],
          scriptEnv(mock),
        )
        assert(result.status === 0, result.stderr || result.stdout)
        assert(
          result.stdout.includes("context zai-org/GLM-5.1: 200000 (from CLI contextWindow)"),
          `expected a per-step context annotation naming the CLI source, got stdout: ${result.stdout}`,
        )
        const mod = await import(out)
        assertEqual(mod.MODEL_SNAPSHOT[0].contextLength, 200000)
        assertEqual(mod.MODEL_SNAPSHOT[0].contextSource, "cli")
        assertEqual(mod.MODEL_SNAPSHOT[0].name, "GLM-5.1")
        assertEqual(mod.MODEL_SNAPSHOT[0].cost, {
          input: 1.4,
          output: 4.4,
          cacheRead: 0.26,
          cacheWrite: 0,
        })
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "a missing price cell fails loudly after the full cost ladder when no source has rates (costs never carry forward)",
    async () => {
      // Issue #132 cost ladder: models.md (—) → models page index → detail
      // page → RSC rates. With none of the enrichment sources configured the
      // row is unshippable — a LOUD failure naming it, never a zero-fill and
      // never a pending note. Missing must never read as free.
      const dir = await mkdtemp(join(tmpdir(), "cc-cost-ladder-fail-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: API_MODELS,
        registry: { "dist-tags": { latest: "1.49.1" } },
        factsMd:
          "## Open Source\n\n" +
          "| Id (use EXACTLY this) | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
          "|---|---|---|---|---|---|---|\n" +
          "| `a/model` | A Model | 1M | low | — | Go and above | best |\n",
        modalitiesBundle:
          'const models={A:{name:"A Model",id:"a/model",inputModalities:["text"],contextWindow:1e6}}',
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", join(dir, "facts.ts")],
          scriptEnv(mock),
        )
        assert(result.status !== 0, `expected non-zero exit, got ${result.status}`)
        assert(
          result.stderr.includes("a/model") &&
            result.stderr.includes("no cost after the full fallback ladder"),
          `expected a loud unshippable-row failure naming the model, got stderr: ${result.stderr}`,
        )
        assert(
          /costs never carry forward/i.test(result.stderr),
          `the loud failure must state that costs never carry forward, got: ${result.stderr}`,
        )
        let wrote = true
        try {
          await readFile(out, "utf-8")
        } catch {
          wrote = false
        }
        assert(!wrote, "no module must be written for an unshippable row")
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "an unknown Context token in the package table fails loudly (pinned decimal table)",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-ctx-unknown-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: API_MODELS,
        registry: { "dist-tags": { latest: "1.49.1" } },
        factsMd:
          "## Open Source\n\n" +
          "| Id (use EXACTLY this) | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
          "|---|---|---|---|---|---|---|\n" +
          "| `a/model` | A Model | 1.5G | low | $1/$2 · cache $0.1 | Go and above | best |\n",
        modalitiesBundle: CLI_BUNDLE,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", join(dir, "facts.ts")],
          scriptEnv(mock),
        )
        assert(result.status !== 0, `expected non-zero exit, got ${result.status}`)
        assert(
          result.stderr.includes("could not parse context cell"),
          `expected loud context-token failure, got stderr: ${result.stderr}`,
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "an unparseable price cell fails loudly (missing uses an em dash)",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-price-parse-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: API_MODELS,
        registry: { "dist-tags": { latest: "1.49.1" } },
        factsMd:
          "## Open Source\n\n" +
          "| Id (use EXACTLY this) | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
          "|---|---|---|---|---|---|---|\n" +
          "| `a/model` | A Model | 1M | low | $nope/$2 · cache $0.1 | Go and above | best |\n",
        modalitiesBundle: CLI_BUNDLE,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", join(dir, "facts.ts")],
          scriptEnv(mock),
        )
        assert(result.status !== 0, `expected non-zero exit, got ${result.status}`)
        assert(
          result.stderr.includes("could not parse price cell"),
          `expected loud price failure, got stderr: ${result.stderr}`,
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "refresh-snapshot fails loudly when the registry body is not JSON",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-registry-parse-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: API_MODELS,
        registryRaw: "<html>not json</html>",
        factsMd: PACKAGE_MD,
        modalitiesBundle: CLI_BUNDLE,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", join(dir, "facts.ts")],
          scriptEnv(mock),
        )
        assert(result.status !== 0, `expected non-zero exit, got ${result.status}`)
        assert(
          result.stderr.includes("could not parse"),
          `expected 'could not parse' in stderr, got: ${result.stderr}`,
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "a CLI bundle omitting a package model logs a modalities-pending note, not a failure (issue #132 moves it to a pending-report)",
    async () => {
      const dir = await mkdtemp(join(tmpdir(), "cc-modalities-pending-"))
      const out = join(dir, "snapshot.ts")
      const mock = await startMockCc({
        models: API_MODELS,
        registry: { "dist-tags": { latest: "1.49.1" } },
        factsMd:
          "## Open Source\n\n" +
          "| Id (use EXACTLY this) | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
          "|---|---|---|---|---|---|---|\n" +
          "| `claude-sonnet-5` | Claude Sonnet 5 | 1M | low, medium, high, xhigh, max | $2/$10 · cache $0.2 (write $2.5) | Pro and above | best |\n" +
          "| `no-cli/model` | No CLI | 1M | low | $1/$2 · cache $0.1 | Go and above | best |\n",
        modalitiesBundle: CLI_BUNDLE,
      })
      try {
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", join(dir, "facts.ts")],
          scriptEnv(mock),
        )
        assert(
          result.status === 0,
          `expected success with a pending note, got stderr: ${result.stderr}`,
        )
        assert(
          result.stdout.includes("modalities pending") && result.stdout.includes("no-cli/model"),
          `expected modalities-pending note, got stdout: ${result.stdout}`,
        )
        const mod = await import(out)
        assert(
          mod.MODEL_SNAPSHOT.some((m) => m.id === "no-cli/model"),
          "a package row must still ship when the CLI bundle omits it",
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],

  [
    "a double-missing row (Context AND price cells missing) resolves context via RSC and fails loudly on cost when no source has rates",
    async () => {
      // The context ladder resolves the missing Context cell via the RSC
      // slug records (the RSC step precedes CLI/LKG). The cost ladder finds
      // no rates anywhere (page/detail/RSC absent) and fails loudly —
      // unshippable row, never zero-filled.
      const dir = await mkdtemp(join(tmpdir(), "cc-double-missing-"))
      const out = join(dir, "snapshot.ts")
      const factsOut = join(dir, "facts.ts")
      const slugPayload = (records) => `2:${JSON.stringify(records)}\n`
      const rscRecord = {
        slug: "double-missing",
        id: "double/missing",
        name: "Double Missing",
        vendor: "double",
        category: "opensource",
        minPlanName: "Go",
        contextWindow: 333000,
        tiers: [],
        caps: {},
        reasoning: false,
      }
      const mock = await startMockCc({
        models: API_MODELS,
        registry: { "dist-tags": { latest: "1.49.1" } },
        factsMd:
          "## Open Source\n\n" +
          "| Id (use EXACTLY this) | Name | Context | Efforts | $/1M in/out · cache read | Min plan | Best for |\n" +
          "|---|---|---|---|---|---|---|\n" +
          "| `double/missing` | Double Missing | — | — | — | Go and above | best |\n",
        modalitiesBundle:
          'const models={DM:{name:"Double Missing",id:"double/missing",inputModalities:["text"],contextWindow:1e6}}',
        rscGoat: slugPayload([rscRecord]),
        rscPro: slugPayload([rscRecord]),
      })
      try {
        const env = {
          ...scriptEnv(mock),
          COMMANDCODE_RSC_GOAT_URL: `${mock.url}/docs/plans/goat`,
          COMMANDCODE_RSC_PRO_URL: `${mock.url}/docs/plans/pro`,
        }
        const result = await runScript(
          ["scripts/refresh-snapshot.mjs", "--out", out, "--facts-out", factsOut],
          env,
        )
        assert(result.status !== 0, `expected non-zero exit, got ${result.status}`)
        assert(
          result.stdout.includes("context double/missing: 333000 (from RSC contextWindow)"),
          `expected the RSC context step to resolve first, got stdout: ${result.stdout}`,
        )
        assert(
          result.stderr.includes("double/missing") &&
            result.stderr.includes("no cost after the full fallback ladder"),
          `expected a loud cost failure naming the row, got stderr: ${result.stderr}`,
        )
      } finally {
        await mock.close()
        await rm(dir, { recursive: true, force: true })
      }
    },
  ],
])
