// src/deals/catalog.ts — GENERATED by scripts/refresh-deals.mjs. Do not edit.
//
// Deal/allowance/benchmark intelligence parsed from the Command Code docs
// site (pricing-limits, plans/goat, plans/pro). Bundled so the plugin can
// enrich the model picker, the sidebar panel, and the plan summary tool
// without network access at runtime. Regenerate with `npm run refresh:deals`.
//
// PLAN_CATALOG rows are parsed from the pricing-limits usage-limits table;
// rows the table cannot source carry their pin / carry-forward provenance
// comment above the row (issue #229).
//
// Plan identity (PlanId) lives in Core — src/catalog/plans.ts — so the
// provider transport can read an explicit plan pin without importing this
// excisable slice (ADR-0004).

import type { PlanId } from "../catalog/plans.js"

export interface DealRates {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
}

export interface PlanInfo {
  price: number
  credits: number
  window5h: number
  windowWeek: number
  /** Human-facing plan name as shown on the Command Code pricing page. */
  display: string
}

export interface ModelDeals {
  /** $/month credit allowance per plan. Absent plan = no data. */
  allowance?: Partial<Record<PlanId, number>>
  /** Deal metadata. endsAt: ISO date or "while capacity lasts". */
  discount?: { pct: number; endsAt?: string }
  /** Pre-deal list prices (for reference). */
  was?: { input: number; output: number; cacheRead: number }
  /** Discounted deal prices (what you pay now). */
  now?: { input: number; output: number; cacheRead: number }
  /** Time-varying rates (DeepSeek V4 peak/off-peak). */
  peakOffPeak?: { peak: DealRates; offPeak: DealRates; windows: string }
  /** Higher-context tier rates (docs: MiniMax M3 >512K). */
  overContext?: DealRates
  benchmark?: { intelligence?: number; tokPerSec?: number }
  tier?: "opensource" | "premium"
  free: boolean
}

export const MODEL_DEALS: Readonly<Record<string, ModelDeals>> = {
  "claude-fable-5": { tier: "premium", benchmark: {"intelligence":49.6}, free: false, allowance: {"goat":20,"pro":20} },
  "claude-fable-5-1": { tier: "premium", benchmark: {"intelligence":53.4,"tokPerSec":66.8}, free: false, allowance: {"goat":20,"pro":20} },
  "claude-haiku-4-5-20251001": { tier: "premium", benchmark: {"intelligence":15.4,"tokPerSec":98.4}, free: false, allowance: {"goat":20,"pro":20} },
  "claude-opus-4-7": { tier: "premium", benchmark: {"intelligence":40.7}, free: false, allowance: {"goat":20,"pro":20} },
  "claude-opus-4-8": { tier: "premium", benchmark: {"intelligence":41.8}, free: false, allowance: {"goat":20,"pro":20} },
  "claude-opus-5": { tier: "premium", benchmark: {"intelligence":50.8,"tokPerSec":53.7}, free: false, allowance: {"goat":20,"pro":20} },
  "claude-opus-5-5": { tier: "premium", benchmark: {"intelligence":57.6}, free: false, allowance: {"goat":20,"pro":20} },
  "claude-sonnet-4-6": { tier: "premium", benchmark: {"intelligence":30.1}, free: false, allowance: {"goat":20,"pro":20} },
  "claude-sonnet-5": { tier: "premium", benchmark: {"intelligence":38.2,"tokPerSec":82.8}, free: false, allowance: {"goat":20,"pro":20} },
  "deepseek/deepseek-v4-flash": { tier: "opensource", benchmark: {"intelligence":34.3}, peakOffPeak: {"peak":{"input":0.3,"output":1.2,"cacheRead":0.006,"cacheWrite":0},"offPeak":{"input":0.15,"output":0.6,"cacheRead":0.003,"cacheWrite":0},"windows":"01–04 & 06–10 UTC, Mon–Fri"}, free: false, allowance: {"goat":60,"pro":70} },
  "deepseek/deepseek-v4-flash-fast": { tier: "opensource", free: false, allowance: {"goat":20,"pro":30} },
  "deepseek/deepseek-v4-flash-vision-exp": { tier: "opensource", benchmark: {"intelligence":34.8,"tokPerSec":228.7}, peakOffPeak: {"peak":{"input":0.3,"output":1.2,"cacheRead":0.006,"cacheWrite":0},"offPeak":{"input":0.15,"output":0.6,"cacheRead":0.003,"cacheWrite":0},"windows":"01–04 & 06–10 UTC, Mon–Fri"}, free: false, allowance: {"goat":20,"pro":30} },
  "deepseek/deepseek-v4-pro": { tier: "opensource", benchmark: {"intelligence":36,"tokPerSec":78.6}, peakOffPeak: {"peak":{"input":1.32,"output":3.96,"cacheRead":0.044,"cacheWrite":0},"offPeak":{"input":0.66,"output":1.98,"cacheRead":0.022,"cacheWrite":0},"windows":"01–04 & 06–10 UTC, Mon–Fri"}, free: false, allowance: {"goat":20,"pro":30} },
  "deepseek/deepseek-v4.1-flash": { tier: "opensource", benchmark: {"intelligence":39.5,"tokPerSec":237.4}, peakOffPeak: {"peak":{"input":0.3,"output":1.2,"cacheRead":0.006,"cacheWrite":0},"offPeak":{"input":0.15,"output":0.6,"cacheRead":0.003,"cacheWrite":0},"windows":"01–04 & 06–10 UTC, Mon–Fri"}, free: false, allowance: {"goat":60,"pro":70} },
  "google/gemini-3.1-flash-lite": { tier: "premium", benchmark: {"intelligence":15.6}, free: false, allowance: {"goat":20,"pro":20} },
  "google/gemini-3.5-flash": { tier: "premium", benchmark: {"intelligence":32.6}, free: false, allowance: {"goat":20,"pro":20} },
  "google/gemini-3.5-flash-lite": { tier: "premium", benchmark: {"intelligence":22.2,"tokPerSec":370}, free: false, allowance: {"goat":20,"pro":20} },
  "google/gemini-3.6-flash": { tier: "premium", benchmark: {"intelligence":34}, free: false, allowance: {"goat":20,"pro":20} },
  "google/gemini-3.7-flash": { tier: "opensource", benchmark: {"intelligence":39.1}, free: false, allowance: {"goat":40,"pro":50} },
  "google/gemini-3.8-flash": { tier: "premium", benchmark: {"intelligence":40.9,"tokPerSec":342.8}, free: false, allowance: {"goat":40,"pro":50} },
  "gpt-5.3-codex": { tier: "premium", benchmark: {"intelligence":32.5,"tokPerSec":145.5}, free: false, allowance: {"goat":20,"pro":20} },
  "gpt-5.4": { tier: "premium", benchmark: {"intelligence":39}, free: false, allowance: {"goat":20,"pro":20} },
  "gpt-5.4-mini": { tier: "premium", benchmark: {"intelligence":24.1}, free: false, allowance: {"goat":20,"pro":20} },
  "gpt-5.5": { tier: "premium", benchmark: {"intelligence":38.4}, free: false, allowance: {"goat":20,"pro":20} },
  "gpt-5.6-luna": { tier: "opensource", benchmark: {"intelligence":37.3,"tokPerSec":140.7}, overContext: {"input":0.4,"output":1.8,"cacheRead":0.04,"cacheWrite":0.5}, free: false, allowance: {"goat":20,"pro":30} },
  "gpt-5.6-sol": { tier: "opensource", benchmark: {"intelligence":47,"tokPerSec":63.8}, overContext: {"input":10,"output":45,"cacheRead":1,"cacheWrite":12.5}, free: false, allowance: {"goat":70,"pro":80} },
  "gpt-5.6-terra": { tier: "premium", benchmark: {"intelligence":42.1,"tokPerSec":90.3}, overContext: {"input":4,"output":18,"cacheRead":0.4,"cacheWrite":5}, free: false, allowance: {"goat":20,"pro":20} },
  "gpt-6-astra": { tier: "premium", benchmark: {"intelligence":52.7,"tokPerSec":57.9}, overContext: {"input":20,"output":75,"cacheRead":2,"cacheWrite":25}, free: false, allowance: {"goat":20,"pro":20} },
  "gpt-6-luna": { tier: "opensource", benchmark: {"intelligence":37.3,"tokPerSec":154.5}, overContext: {"input":0.2,"output":0.75,"cacheRead":0.02,"cacheWrite":0.25}, free: false, allowance: {"goat":20,"pro":30} },
  "gpt-6-sol": { tier: "premium", benchmark: {"intelligence":47.5,"tokPerSec":116.3}, overContext: {"input":4,"output":15,"cacheRead":0.4,"cacheWrite":5}, free: false, allowance: {"goat":20,"pro":20} },
  "inclusionai/ling-3.0-flash-sante:free": { tier: "opensource", free: true },
  "meituan/LongCat-2.0": { tier: "opensource", benchmark: {"intelligence":19.1}, free: false, allowance: {"goat":50,"pro":60} },
  "meta/muse-spark-1.1": { tier: "premium", benchmark: {"intelligence":33.7}, free: false, allowance: {"goat":20,"pro":20} },
  "meta/muse-spark-1.2": { tier: "opensource", benchmark: {"intelligence":39.6}, free: false, allowance: {"goat":20,"pro":30} },
  "meta/muse-spark-1.2-contributor": { tier: "opensource", benchmark: {"intelligence":39.6}, free: false, allowance: {"goat":20,"pro":30} },
  "meta/muse-spark-1.3": { tier: "premium", benchmark: {"intelligence":48.1,"tokPerSec":247.5}, free: false, allowance: {"goat":20,"pro":30} },
  "meta/muse-spark-1.3-contributor": { tier: "premium", benchmark: {"intelligence":48.1,"tokPerSec":247.5}, free: false, allowance: {"goat":20,"pro":30} },
  "MiniMaxAI/MiniMax-M2.5": { tier: "opensource", benchmark: {"intelligence":22.8}, free: false, allowance: {"goat":20,"pro":30} },
  "MiniMaxAI/MiniMax-M2.7": { tier: "opensource", benchmark: {"intelligence":22.8}, free: false, allowance: {"goat":20,"pro":30} },
  "MiniMaxAI/MiniMax-M3": { tier: "opensource", discount: {"pct":50}, was: {"input":0.6,"output":2.4,"cacheRead":0.12}, now: {"input":0.3,"output":1.2,"cacheRead":0.06}, benchmark: {"intelligence":29.2,"tokPerSec":159.3}, free: false, allowance: {"goat":47,"pro":57} },
  "moonshotai/Kimi-K2.5": { tier: "opensource", benchmark: {"intelligence":23.5}, free: false, allowance: {"goat":20,"pro":30} },
  "moonshotai/Kimi-K2.6": { tier: "opensource", benchmark: {"intelligence":27}, free: false, allowance: {"goat":20,"pro":30} },
  "moonshotai/Kimi-K2.7-Code": { tier: "opensource", benchmark: {"intelligence":25.8,"tokPerSec":52.4}, free: false, allowance: {"goat":60,"pro":70} },
  "moonshotai/Kimi-K2.7-Code-Highspeed": { tier: "opensource", free: false, allowance: {"goat":20,"pro":30} },
  "moonshotai/Kimi-K3": { tier: "opensource", benchmark: {"intelligence":43.6,"tokPerSec":37.7}, free: false, allowance: {"goat":20,"pro":30} },
  "nvidia/nemotron-3-ultra-550b-a55b": { tier: "opensource", benchmark: {"intelligence":22.9,"tokPerSec":159.3}, free: false, allowance: {"goat":20,"pro":30} },
  "poolside/laguna-s-2.1-free": { tier: "opensource", free: true },
  "Qwen/Qwen3.6-Max-Preview": { tier: "opensource", benchmark: {"intelligence":28.4}, free: false, allowance: {"goat":20,"pro":30} },
  "Qwen/Qwen3.6-Plus": { tier: "opensource", benchmark: {"intelligence":27}, overContext: {"input":2,"output":6,"cacheRead":0.2,"cacheWrite":0}, free: false, allowance: {"goat":33,"pro":43} },
  "Qwen/Qwen3.7-Flash": { tier: "opensource", overContext: {"input":0.2,"output":0.8,"cacheRead":0.04,"cacheWrite":0.25}, free: false, allowance: {"goat":20,"pro":30} },
  "Qwen/Qwen3.7-Max": { tier: "opensource", discount: {"pct":50,"endsAt":"2026-06-22"}, was: {"input":5,"output":15,"cacheRead":1}, now: {"input":2.5,"output":7.5,"cacheRead":0.5}, benchmark: {"intelligence":29.5}, free: false, allowance: {"goat":33,"pro":43} },
  "Qwen/Qwen3.7-Plus": { tier: "opensource", benchmark: {"intelligence":25.2,"tokPerSec":61.9}, overContext: {"input":1.2,"output":4.8,"cacheRead":0.24,"cacheWrite":1.5}, free: false, allowance: {"goat":33,"pro":43} },
  "Qwen/Qwen3.8-27B": { tier: "opensource", benchmark: {"intelligence":33.7,"tokPerSec":46.5}, free: false, allowance: {"goat":70,"pro":80} },
  "Qwen/Qwen3.8-Flash": { tier: "opensource", free: false, allowance: {"goat":20,"pro":30} },
  "Qwen/Qwen3.8-Max": { tier: "opensource", benchmark: {"intelligence":40.2}, free: false, allowance: {"goat":20,"pro":30} },
  "Qwen/Qwen3.8-Max-0902": { tier: "opensource", benchmark: {"intelligence":45.4,"tokPerSec":41.6}, free: false, allowance: {"goat":20,"pro":30} },
  "Qwen/Qwen3.8-Omni-Flash": { tier: "opensource", free: false, allowance: {"goat":20,"pro":30} },
  "sakana/fugu-ultra": { tier: "premium", free: false, allowance: {"goat":20,"pro":20} },
  "stealth/pixel-canary": { tier: "opensource", free: true },
  "stealth/space-bunny-alpha": { tier: "opensource", free: true },
  "stepfun/Step-3.5-Flash": { tier: "opensource", benchmark: {"intelligence":17}, free: false, allowance: {"goat":20,"pro":30} },
  "stepfun/Step-3.7-Flash": { tier: "opensource", benchmark: {"intelligence":19.5,"tokPerSec":196.7}, free: false, allowance: {"goat":20,"pro":30} },
  "stepfun/Step-5-Preview": { tier: "opensource", benchmark: {"intelligence":43.7,"tokPerSec":71.1}, free: false, allowance: {"goat":20,"pro":30} },
  "tencent/hy3-paid": { tier: "opensource", benchmark: {"intelligence":25.3,"tokPerSec":92.5}, free: false, allowance: {"goat":70,"pro":80} },
  "tencent/hy4-preview": { tier: "opensource", free: false, allowance: {"goat":20,"pro":30} },
  "thinkingmachines/inkling": { tier: "opensource", benchmark: {"intelligence":25,"tokPerSec":109.2}, free: false, allowance: {"goat":20,"pro":30} },
  "thinkingmachines/inkling-small": { tier: "opensource", benchmark: {"intelligence":27.8,"tokPerSec":230.2}, free: false, allowance: {"goat":20,"pro":30} },
  "xai/grok-4.5": { tier: "opensource", benchmark: {"intelligence":38.8}, free: false, allowance: {"goat":20,"pro":30} },
  "xai/grok-4.6": { tier: "opensource", benchmark: {"intelligence":44.3,"tokPerSec":70.3}, overContext: {"input":4,"output":12,"cacheRead":1,"cacheWrite":0}, free: false, allowance: {"goat":20,"pro":30} },
  "xai/grok-4.7": { tier: "premium", discount: {"pct":40,"endsAt":"2026-09-27"}, was: {"input":2,"output":6,"cacheRead":0.5}, now: {"input":1.2,"output":3.5999999999999996,"cacheRead":0.3}, benchmark: {"intelligence":46.4,"tokPerSec":50.4}, free: false, allowance: {"goat":35,"pro":45} },
  "xiaomi/mimo-v2.5": { tier: "opensource", discount: {"pct":98}, was: {"input":0.8,"output":4,"cacheRead":0.16}, now: {"input":0.14,"output":0.28,"cacheRead":0.0028}, benchmark: {"intelligence":25.2,"tokPerSec":39.5}, free: false, allowance: {"goat":30,"pro":40} },
  "xiaomi/mimo-v2.5-pro": { tier: "opensource", discount: {"pct":99}, was: {"input":2,"output":6,"cacheRead":0.4}, now: {"input":0.435,"output":0.87,"cacheRead":0.0036}, benchmark: {"intelligence":26,"tokPerSec":50.4}, free: false, allowance: {"goat":20,"pro":30} },
  "xiaomi/mimo-v2.6-flash": { tier: "opensource", free: false, allowance: {"goat":20,"pro":30} },
  "xiaomi/mimo-v2.6-pro": { tier: "opensource", benchmark: {"intelligence":46.3,"tokPerSec":54.5}, free: false, allowance: {"goat":20,"pro":30} },
  "xiaomi/mimo-v2.6-pro-ultraspeed": { tier: "opensource", free: false, allowance: {"goat":10,"pro":20} },
  "z-ai/glm-5.3-flash": { tier: "opensource", benchmark: {"intelligence":41.8,"tokPerSec":48.8}, free: false, allowance: {"goat":40,"pro":50} },
  "z-ai/glm-5.3-flashx": { tier: "opensource", free: false, allowance: {"goat":20,"pro":30} },
  "zai-org/GLM-5": { tier: "opensource", benchmark: {"intelligence":27.9}, free: false, allowance: {"goat":20,"pro":30} },
  "zai-org/GLM-5.1": { tier: "opensource", benchmark: {"intelligence":26.1}, free: false, allowance: {"goat":20,"pro":30} },
  "zai-org/GLM-5.2": { tier: "opensource", benchmark: {"intelligence":33.7}, free: false, allowance: {"goat":70,"pro":80} },
  "zai-org/GLM-5.2-Fast": { tier: "opensource", free: false, allowance: {"goat":20,"pro":30} },
  "zai-org/GLM-5.3": { tier: "opensource", benchmark: {"intelligence":44.8,"tokPerSec":63.2}, free: false, allowance: {"goat":20,"pro":30} },
}

export const PLAN_CATALOG: Readonly<Record<PlanId, PlanInfo>> = {
  go: { price: 1, credits: 10, window5h: 3, windowWeek: 6, display: "Go" },
  goat: { price: 10, credits: 70, window5h: 14, windowWeek: 35, display: "GOAT" },
  pro: { price: 20, credits: 80, window5h: 16, windowWeek: 40, display: "Pro" },
  // Legacy Pro: the docs table's row before the Aug 2026 repricing, kept
  // for grandfathered individual-pro accounts (issue #162). Source:
  // https://web.archive.org/web/20260803033612/https://commandcode.ai/docs/resources/pricing-limits
  // Docs allowances stay keyed pro, so this row has no allowance table.
  prolegacy: { price: 15, credits: 30, window5h: 9, windowWeek: 18, display: "Pro (legacy)" },
  max: { price: 100, credits: 150, window5h: 45, windowWeek: 90, display: "Max 10×" },
  max20: { price: 200, credits: 300, window5h: 90, windowWeek: 180, display: "Max 20×" },
  teampro: { price: 40, credits: 40, window5h: 12, windowWeek: 24, display: "Team Pro" },
  // Provider: pinned — the usage-limits table has no Provider row, because
  // the plan is pay-as-you-go API access: no monthly credits or window
  // caps. The $15/mo price and PAYG terms are from
  // https://commandcode.ai/provider (the marketing table's Provider row
  // carries the price but prose, not plan figures).
  provider: { price: 15, credits: 0, window5h: 0, windowWeek: 0, display: "Provider" },
}

export const DEAL_SOURCE_URL = "https://commandcode.ai/docs/resources/pricing-limits"
export const DEAL_LAST_REFRESHED = "2026-09-26"
export const DEAL_PACKAGE_VERSION = "docs"
